### ISSUE TITLE
Direct blow can make Tandem Charge SRMs fail

### ISSUE THREAD

**Issue by IReallyHateGithub** [MegaMek/megamek#297] opened 2016-08-02 19:09 UTC
There seems to be some inconsistency in how Tandem Charge SRM ammo operates. It should be getting a penalized critical chance on every hit instance, but this is not consistently applied to every TC SRM hit.

http://pastebin.com/qDWHzCzQ

As you can see in the above log, the Warhammer's Tandem Charge SRM strikes get the proper crit chances. the Timber Wolf's hit log does not report any chances at a critical hit.

When I advance the test game a turn, and make them fire on each other again, both got their proper chance at critical hits.

**Comment by IReallyHateGithub** [comment] 2016-08-02 19:38
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/397960/autosave.sav.gz)

Attached an autosave as per request

**Comment by arlith** [comment] 2016-08-02 20:13
The problem stems from `Server.handleEntityDamage` around line 22493.  Around this point, it checks to see if the `HitData` has a "special critical" (from things like TCs or AP ammo).  The problem is, the check is `hit.getSpecCritMod() < 0`.  If direct blow is on, the special crit mod could potentially be 0, causing the check to fail.

The fix for this is to store an additional boolean flag to indicate if there's a special crit, as well as the int critical roll modifier.

**Closed** 2016-08-02 20:22 UTC
