### ISSUE TITLE
Aircraft displays 0 fuel when loading specific saved game

### ISSUE THREAD

**Issue by NickAragua** [MegaMek/megamek#658] opened 2017-09-18 00:38 UTC
Using nightly build 360, loading a saved game (created six days ago off of "bleeding edge" code at the time) with an active aircraft on the board, the aircraft (dagger way on the south of the map) displays as having 0 fuel. Probably needs some edge case bulletproofing.

[1Mek1AircraftEdgeTesting.sav.gz](https://github.com/MegaMek/megamek/files/1309490/1Mek1AircraftEdgeTesting.sav.gz)

**Comment by pheonixstorm** [comment] 2017-09-18 00:59
nightly build 360?? post in contrib channel where you grabbed that one, doesn't match the number form either jenkins.

**Comment by arlith** [comment] 2017-09-18 01:42
If you're loading a saved come from a prior version into a newer version, this is probably due to the changes in PR #642.  You should try starting the game with a new build and see if the issue persists.  I'm guessing this issue comes from loading a saved game from a previous version.  Generally, we don't support these kinds of issues.  Things can change across versions, and usually people will finish their saved game in one version and start a new game in the next version.

**Comment by arlith** [comment] 2017-09-18 13:52
This was confirmed by @mkerensky as being a savedgame from previous version issue.  Going to close this as wont-fix.

**Closed by arlith** 2017-09-18 13:52 UTC
Labels: wontfix
