### ISSUE TITLE
49.19.1 BMM Flamers - Apply heat when Roll to Hit is on Leg behind cover & No Damage. 

### ISSUE THREAD

**Issue by PirateofMRC** [MegaMek/megamek#5778] opened 2024-07-23 16:21 UTC
### Environment
49.19.1
Win 10
Java 11 on server running Java 17

### Description
Flamers from BA targeting a mech with Partial Cover. BMM Flamers is on doing heat and damage. When hitting LEGS, No damage applied, but heat is applied. In this situation, heat should not be applied as roll to hit was made? Page 99 of BMM manual states if a hit is made, t applies both. But in this case hit is made to a leg behind cover so no damage is made. 

![image](https://github.com/user-attachments/assets/072d92f1-e606-4701-bbba-f6cc251eec0b)
[Round-12-autosave_2024-07-23_15-05-07.sav.gz](https://github.com/user-attachments/files/16351608/Round-12-autosave_2024-07-23_15-05-07.sav.gz)

### Files
Savegame attached, but it is from a few turns later, did not think to save at time for bug purposes. probabbly repeatable as it happened 2 times during this gam e(first was unnoticed at round 4, other at round 9, attached is round 12 autosave)
[megamek.log](https://github.com/user-attachments/files/16351613/megamek.log)

**Comment by neoancient** [comment] 2024-08-20 18:06
Duplicate of #5777

**Closed by neoancient** 2024-08-20 18:06 UTC
Labels: Bug, Errata, Duplicate
