### ISSUE TITLE
Hatchets missing -1 to Hit modifier

### ISSUE THREAD

**Issue by monbvol** [MegaMek/megamek#59] opened 2016-03-04 22:52 UTC
Hatchets are missing their inherent -1 to Hit modifier in MegaMek.

**Comment by arlith** [comment] 2016-03-05 00:39
It is really convenient in these cases to attach a saved game, even if the bug is "easy to reproduce."  Even if I can reproduce the issue quickly, it still saves me the few minutes it takes to get a game setup with some units, and get to the point where I can reproduce the bug.

And then, there are cases like this where I cannot reproduce the bug.  I looked at the code and I can see where the modifier is applied, and when I started up a game I was able to witness the modifier being applied.  It is worth noting though that there's a specific "Hatchet" button that you need to use; punching won't show the modifier (as it shouldn't apply).

Beyond that, what unit were you using?  Could you supply a save?

**Comment by arlith** [comment] 2016-03-21 15:37
I couldn't find any issues here, and I never got a reply from the OP.  I'm going to close this ticket.

**Closed** 2016-03-21 15:38 UTC
Labels: bug
