### ISSUE TITLE
Ejected ASF Pilot not correctly logged

### ISSUE THREAD

**Issue by Menzius** [MegaMek/megamek#76] opened 2016-03-12 08:48 UTC
I played a AtB chase (defend) scenario and deployed a Mech Star and an ASF Flight in MekHQ. During the battle one of my fighters crashed without exploding after failing her heat-related PSR.During the next turn I ejected the pilot, who was unharmed at this point. The game was won soon after (I used /victory) and the usuall resolve scenario dialog in MekHQ opened up which wrongly showed the ejected Pilot as dead. After checking the gamelog I think the pilot ejected successfully but was not correctly saved/written in the log as having ejected but simply vanished. An enemy Mech Warrior ejected during the same game and was correctly displayed.

- MlHQ 0.3.25, MegaMek 0.41.15
- conditions were calm
- Ejected Pilots Flee is enabled
- only checked boxes in the Aerospace Tab are 
"allow aerospace units on ground maps"
"allow return flyovers"

In the attached .zip are:
- the complete gamelog.html, search for Stuka
- save during the game before the crash "asd"
- autosave before I declared victory

This issue is obviously not a priority since the user should check and correct the resolve dialog in MekHQ and an ejected Pilot does not contribute to the specific MegaMek game anyway.

[12032016 ASF pilot bug.zip](https://github.com/MegaMek/megamek/files/170331/12032016.ASF.pilot.bug.zip)

**Comment by Question2** [comment] 2016-04-01 06:12
Ive had a battle where an unconcious pilot crashed 4 elevation levels and then had the ASF destroyed by structural collaspe, but he still survived.

**Comment by arlith** [comment] 2016-08-03 00:13
I think this is a duplicate issue for [SF MHQ #815](https://sourceforge.net/p/mekhq/bugs/815/).  In that bug, if the "Ejected Pilots flee" option is turned on, then the pilots aren't recovered in MHQ.  When I loaded your saved game, that option was turned on.  I'm going to consider this ticket a duplicate of that.

**Closed by arlith** 2016-08-03 00:13 UTC
