### ISSUE TITLE
SemiGuided LRMs Indirect Fire and Terrain

### ISSUE THREAD

**Issue by strategoslevel3** [MegaMek/megamek#4638] opened 2023-07-17 22:51 UTC
0.49.13 MacOS

Playing with 0.49.13 today using Semi-Guided Missiles.  Found a bug.  Firing with indirect fire after the target has been Tagged, there should be no terrain modifiers but the mod for 2 hexes of light smoke is still being applied.

![Screenshot_2023-07-17_at_23 13 52](https://github.com/MegaMek/megamek/assets/67537490/76d4a570-9c10-4416-b5a7-c6109c7d8f03)
<img width="387" alt="Screenshot_2023-07-17_at_23 22 28" src="https://github.com/MegaMek/megamek/assets/67537490/2527f116-119c-460f-983a-6c935ecbf928">

**Comment by HammerGS** [comment] 2023-07-17 22:53
Related and possible duplicate of https://github.com/MegaMek/megamek/issues/4459

**Closed** 2023-07-21 10:06 UTC
Labels: Bug, Errata
