### ISSUE TITLE
Outofbounds java error

### ISSUE THREAD

**Issue by Garthok2962** [MegaMek/megamek#4499] opened 2023-06-07 21:36 UTC
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
Version 0.49.13, Standalone Megamek, Windows. Java Version 17.0.4
### Description
When Joining a game with any custom meks The out of bounds error occurs
### Files
[12th_Arvus_Rangers30360922.cpnx.gz](https://github.com/
[megamek.log](https://github.com/MegaMek/megamek/files/11682131/megamek.log)
MegaMek/megamek/files/11682129/12th_Arvus_Rangers30360922.cpnx.gz)
12th_Arvus_Rangers

**Comment by HammerGS** [comment] 2023-06-07 22:01
You are going to need to create a single zip file for these.

**Comment by kuronekochomusuke** [comment] 2023-06-07 22:03
looks to be a duplicate of #4460

**Comment by repligator** [comment] 2024-07-20 22:48
Duplicate of a closed issue, closing.

**Closed by repligator** 2024-07-20 22:48 UTC
Labels: Duplicate
