### ISSUE TITLE
Several Movement Options are Missing for Protomechs

### ISSUE THREAD

**Issue by BrandonSmith16** [MegaMek/megamek#6066] opened 2024-10-04 23:45 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

Climb Mode among others is missing. Climb mode would be used to determine if the mech enters or climbs the building. 

### Steps to Reproduce

Load a protomech into the game. 

### Operating System *

Windows 10

### Java Version *

17.7

### MegaMek Suite Version *

v0.50.0

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by SJuliez** [comment] 2024-10-31 08:01
duplicate of #6067

**Closed by SJuliez** 2024-10-31 08:01 UTC
Labels: ProtoMek, Severity: Medium
