### ISSUE TITLE
Dropships using bay weapons in the air incompatible with weapon specialist SPA

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#206] opened 2016-05-19 05:23 UTC
Even if you have the unofficial rule checked, when editing a dropship pilot in the megamek lobby, the weapon specialist SPA only allows you to use weapons by bay (e.g. artillery bay, PPC bay, laser bay, etc) instead of the individual weapons that you would be using (arrow IV, ER PPC, Large Laser, etc). You can set it to weapon specialist (artillery bay) but it has no effect when the grounded dropship is attempting to fire the individual weapons when grounded (such as arrow IV).

The dropship in the save was set to weapon specialist (artillery bay) in the lobby.

[#battletech.zip](https://github.com/MegaMek/megamek/files/271891/battletech.zip)

**Comment by BLOODWOLF333** [comment] 2016-05-20 02:13
Tested, under the right-click menu in the lobby on the dropship, configure, deployment tab:  If it starts at altitude 5(default) then weapon specialist will only apply to bay weapon types because those are what will be listed in the units data.  If you set the dropships altitude to 0, click ok, then configure again now you can set weapon specialist to the specific weapons like pulse laser etc since it will be deployed landed.  But it wont do both as is.

**Comment by Question2** [comment] 2016-05-20 13:21
Thanks, you are right, that works as a workaround.

**Comment by arlith** [comment] 2016-05-31 15:41
This is a tricky issue, as the UI display for the Weapon Specialist SPA only displays weapons that the unit actually has.  The weapons that the unit actually has is based upon altitude with the "grounded dropships use individual weapons" rule is on.  When the DS isn't grounded, it has bays for weapons.  When it's grounded, instead of bays for weapons, it has a list of individual weapons.  This seems to be a bit of a thorny issue.

**Comment by pheonixstorm** [comment] 2016-06-01 02:40
aToW does specify that you can take weapon specialist more than once. Maximum gunnery SPAs allowed is 3 based on aToW. Would it be difficult to set a maximum number of allowed weapon specializations?Then the issue is moot as you can specialize in a bay and specific weapon when grounded.

That or check for whats in the bay and randomly switch to a weapon equipped to that bay (or longest range weapon)

**Comment by SJuliez** [comment] 2023-06-08 14:00
@HammerGS Looking at this old issue, it is no longer unofficial. I'm wondering why Weapon Specialist should ever allow choosing a whole bay rather than a weapon. CamOps doesn't suggest anything like that. So, my take would be to only allow individual weapons to be chosen. This would mean however that bays would not receive a bonus from the SPA regardless of the chosen weapon. Any thoughts on space battles with this SPA?

**Comment by HammerGS** [comment] 2023-06-08 14:03
I don't think it should. But I'll make a question behind the scenes.

**Comment by HammerGS** [comment] 2023-06-08 18:52
The answer is back - SPA's are applicable to Weapon Bays providing the bay contains ALL the same type of Weapon type for example - all PPC's, or all ER PPC's.  

From CO pg 82 
_When acquiring this ability, the warrior must identify a **specific weapon** as their ultimate “weapon of choice” in battle._

But the bay is considered a specific weapon. So a Weapon Specialist would be - PPC Bay, or ER PPC bay. They don't also get a SPA for just a PPC or ER PPC.

**Closed** 2023-06-21 15:21 UTC
Labels: Bug, Aerospace, Rules Question, DropShip
