### ISSUE TITLE
0.47.4 Map Editor - 'Resize Map' button behaviour inconsistent

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#1764] opened 2020-03-14 02:37 UTC
The 'Resize Map' button does not seem to act in a predictable fashion - when set to e.g. add 17 rows to the 'North' edge, it resized a 64x68 map to a 16x34 map.

17 rows were indeed added to the North edge, but 51 were removed from the South, and 48 were removed from the East, despite no change having been made to those values.

(This looks like it might have been an extant bug in 0.46.1, so may well be a pre-existing issue, rather than being specific to 0.47.4.)

**Comment by Windchild292** [comment] 2020-03-14 02:51
I cannot recreate this in latest development branch, but I do not remember a specific fix. I'd say keep this open as a reminder to check once the next release happens.

**Comment by SJuliez** [comment] 2020-03-14 06:16
I can't reproduce this.

**Comment by SimonLandmine** [comment] 2020-03-14 12:33
I'll do it again today, and see whether it replicates exactly. With screenshots. Thanks!

**Comment by Windchild292** [comment] 2020-03-14 12:37
It might be fixed in develop but not in 0.47.4, I'll check that release in a bit

**Comment by Windchild292** [comment] 2020-03-14 13:40
I cannot recreate this in 0.47.4 either, waiting for instructions to continue

**Comment by SJuliez** [comment] 2020-04-09 16:30
I have now worked quite a bit with the Resize Map dialog and couldn't find any misbehaviour (at least regarding this issue). So I'm closing this now. Dear @SimonLandmine please reopen if this happens again.

**Closed by SJuliez** 2020-04-09 16:30 UTC
Labels: Map Editor

**Comment by SimonLandmine** [comment] 2020-04-09 17:33
Wilco
