### ISSUE TITLE
NPE in Princess-precognition while Player uses ASF in AtB play.

### ISSUE THREAD

**Issue by Menzius** [MegaMek/megamek#306] opened 2016-08-09 15:08 UTC
During my last AtB scenario Princess froze right after one of my ASFs returned to the map. I fixed the issue by kicking the concerned bot and replacing it (default bot settings). The log shows the following:

Exception in thread "Princess-precognition (Clan Jade Falcon (Reinforcements))" java.lang.NullPointerException
	at megamek.client.bot.princess.Precognition.dirtifyUnit(Precognition.java:576)
	at megamek.client.bot.princess.Precognition.processGameEvents(Precognition.java:528)
	at megamek.client.bot.princess.Precognition.run(Precognition.java:420)

This might not be related to ASFs at all but it is the only thing that I can think of that changed prior to the freeze. Also the ASF did return after failing a maneuver not after me flying it off the map. 
Attached are mekhqlog.txt, gamelog and savegame, all up to the point of the freeze:
[NPE logs.gz](https://github.com/MegaMek/megamek/files/409226/NPE.logs.gz)

**Comment by HammerGS** [comment] 2016-08-09 15:37
The log actually has a a few different errors in it:
Line 684
`Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index: 2, Tab count: 1
	at javax.swing.JTabbedPane.checkIndex(Unknown Source)
	at javax.swing.JTabbedPane.setSelectedIndex(Unknown Source)
	at megamek.client.ui.swing.CustomMechDialog.setSelectedTab(CustomMechDialog.java:734)
	at megamek.client.ui.swing.ChatLounge.customizeMechs(ChatLounge.java:2370)
	at megamek.client.ui.swing.ChatLounge$MekTableMouseAdapter.actionPerformed(ChatLounge.java:3698)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)`

Line 6950: 2 identical back to back errors:
`java.io.FileNotFoundException: savegames\autosave.sav.gz (Der Vorgang ist bei einer Datei mit einem ge��eten Bereich, der einem Benutzer zugeordnet ist, nicht anwendbar)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at megamek.server.Server.saveGame(Server.java:1350)
	at megamek.server.Server.autoSave(Server.java:1284)
	at megamek.server.Server.prepareForPhase(Server.java:2529)
	at megamek.server.Server.changePhase(Server.java:2324)
	at megamek.server.Server.endCurrentPhase(Server.java:2866)
	at megamek.server.Server.changePhase(Server.java:2333)
	at megamek.server.Server.endCurrentPhase(Server.java:3070)
	at megamek.server.Server.checkReady(Server.java:2103)
	at megamek.server.Server.handle(Server.java:29768)
	at megamek.server.Server$PacketPump.run(Server.java:353)
	at java.lang.Thread.run(Unknown Source)`

and lastly the section Menzius copies above:
Line 6986:
`Exception in thread "Princess-precognition (Clan Jade Falcon (Reinforcements))" java.lang.NullPointerException
	at megamek.client.bot.princess.Precognition.dirtifyUnit(Precognition.java:576)
	at megamek.client.bot.princess.Precognition.processGameEvents(Precognition.java:528)
	at megamek.client.bot.princess.Precognition.run(Precognition.java:420)`

**Comment by pheonixstorm** [comment] 2016-08-09 21:01
This wouldn't be an AtB issue as AtB is purely MekHQ

**Comment by arlith** [comment] 2016-08-10 02:57
The `ArrayIndexOutOfBoundsException` is fixed with 40afe2b.

**Comment by arlith** [comment] 2016-08-10 03:03
This is the line that is causing the NPE in `Precognition.dirtifyUnit`

```java
                TreeSet<Integer> toDirty = new TreeSet<>(getPathEnumerator()
                        .getEntitiesWithLocation(
                                getGame().getEntity(id).getPosition(), true));
```

There is a check earlier to ensure `getGame().getEntity(id)` is non-null, however it's not clear to me that threading couldn't cause issues here.  That's really the only thing that makes sense as I don't think that the `PathEnumerator` can be null, but maybe that could also happen.

**Comment by kipstafoo** [comment] 2016-08-24 16:36
Yeah, this happens to me at least once a game. This seems to be related to, at least for me, vehicles that have become immobile and the crews have ejected.

**Closed** 2016-08-25 15:15 UTC
Labels: bug, Princess

**Comment by arlith** [comment] 2016-08-25 15:23
The issue here has to do with thread-safety.  `Princess.Precognition` has its own `Game` instance that it manages.  This instance is always accessed through `Princess.getGame` which does acquire a lock before returning the instance.  The problem is, there are methods within `Precognition` that change the state of `Game`, but they don't acquire a lock on it.  For instance, `Precognition.handlePacket` receives a packet which will always update `Game`.  This methods needs to acquire a lock on `Game` at the onset, and relinquish the lock at the end.  Like-wise, `Precognition.dirtifyUnit` also needs to acquire a lock.  That's what I did to fix the issue.

Also, I changed the lock mechanism from `ReentrantReadWriteLock` to just `ReentratLock`.  I can't think of any instances where it would be safe to acquire a read or write lock; if `Game` is being updated, it's not safe for anything else to read from it.

Finally, I can't ensure that this actually fixes the issue.  I'm fairly certain I've got it right, but since I the issue is intermittent I can't be 100% sure.  If this issue crops up in 0.41.22 or later, please update this ticket or create a new one.
