### ISSUE TITLE
[0.43.2-git : Bug] VTOL Cannot Fly Over Bridge

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#580] opened 2017-07-31 03:40 UTC
VTOL cannot fly over bridge even when its elevation = 6 while the bridge elevation = 2. Savegame attached.

[VTOLCannotFlyOverBridge.sav.gz](https://github.com/MegaMek/megamek/files/1186332/VTOLCannotFlyOverBridge.sav.gz)

**Comment by neoancient** [comment] 2017-07-31 03:51
This is a duplicate of #483, which was fixed and is working in 0.43.3.

**Closed by neoancient** 2017-07-31 03:51 UTC
Labels: duplicate
