### ISSUE TITLE
doTryUnstuck Error

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#19] opened 2016-02-05 09:03 UTC
MegaMek version 0.41.11

Start of Round 1, before the screen changes to the map, hit the error doTryUnstuck. To replicate, just load the attached savegame.

[doTryUnstuckError.sav.gz.txt](https://github.com/MegaMek/megamek/files/118866/doTryUnstuckError.sav.gz.txt)
[doTryUnstuckErrorLog.txt](https://github.com/MegaMek/megamek/files/118865/doTryUnstuckErrorLog.txt)

**Comment by arlith** [comment] 2016-02-06 02:34
I presume this game was started via MHQ.  Did you end a previous game with a unit stuck in a swamp?  The root cause is that you've got a unit that's stuck in a swamp, but doesn't appear to be deployed yet.  There are a couple of fairly easy fixes for this, however first I'd like to understand how you got a unit to be considered stuck in a swamp before it was deployed.  The most likely case to me is that the isStuckInSwamp state isn't reset by MHQ.

Probably, there should be two fixes: MHQ shoudl reset the isStuckInSwamp state, and also Server.doTryUnstuck should not try to unstick units that aren't deployed.

**Comment by Dylan-M** [comment] 2016-02-06 03:12
Should not try to unstick units? Or rather should auto-succeed with no message because the unit shouldn't be stuck in the first place?

**Comment by SirMegaV** [comment] 2016-02-06 04:45
Yes you are right. It was started from MHQ and the previous game was all swampy. So I guess it was stuck during last game turn. MHQ have to be relaunched only then the game was working normally.

**Comment by arlith** [comment] 2016-02-06 20:27
Fixed in 24f796f.  I did make a commit to MekHQ so that the isStuck state is reset at the end of a game.  It looks like Server.doTryUnstuck did have code for looking to see if an Entity had a null position, but then it checked to see if it was deployed as well.  In that case, it would skip the check and log a message.  I updated that condition so that, if the entity position is null, it checks the unstuck check, however if the unit is deployed, it just prints a log message, if the unit is not deployed it clears the stuck state and logs a different message.  This clears up the crash and I was able to start the movement phase with your saved game.

**Closed** 2016-02-06 20:28 UTC
Labels: bug
