### ISSUE TITLE
PSR triggered (and failed!) mid-jump on 0.43.3

### ISSUE THREAD

**Issue by mhjacks** [MegaMek/megamek#592] opened 2017-08-09 01:22 UTC
In round 4, my Stealth was jumping over a building that collapsed due to enemy movement.  This triggered a PSR on the Stealth, and it fell.

**Comment by mhjacks** [comment] 2017-08-09 01:23
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/1210024/autosave.sav.gz)

**Comment by HammerGS** [comment] 2017-08-09 03:19
This might be related to the WiGE building issue fixed here - https://github.com/MegaMek/megamek/issues/584

**Comment by arlith** [comment] 2017-09-03 21:13
This is a duplicate of #573.

**Closed by arlith** 2017-09-03 21:13 UTC
Labels: bug, duplicate
