### ISSUE TITLE
[0.49.17] Modifier for BAP shooting through woods shows up in wrong places

### ISSUE THREAD

**Issue by EvilAtlas** [MegaMek/megamek#5072] opened 2024-01-22 01:30 UTC
### Environment
MegaMek version 0.49.17, packaged with MekHQ
Windows 11
Java 11.0.14.1

### Description
During the shooting phase, in the section of the unit window where accuracy modifiers are displayed, mechs firing through woods were given the "target behind woods and attacker has BAP" modifier despite none of the mechs having BAPs or pilots with SPAs. I am not yet sure whether this was actually affecting accuracy or if it was just a display bug.

That modifier also appeared, clearly erroneously, in the firing results list. Where it should just state a to-hit number it instead includes "behind woods and attacker has BAP)'>" before that number.

To reproduce, just load into the game and find a position where you'll be shooting through woods. (This should be easy.)

### Files
![Screenshot 2024-01-21 172153](https://github.com/MegaMek/megamek/assets/94950654/ae020f15-90e4-48fa-b5f9-a4cd0e82c169)
![firingreportBAPbug](https://github.com/MegaMek/megamek/assets/94950654/b0571f9b-34db-4f72-ba5b-d3be20db13d1)
[megamek.log](https://github.com/MegaMek/megamek/files/14003576/megamek.log)
[BAPbugsave.sav.gz](https://github.com/MegaMek/megamek/files/14003577/BAPbugsave.sav.gz)
Player name: Evil Atlas

**Comment by kuronekochomusuke** [comment] 2024-01-22 12:37
duplicate of #5030

**Closed** 2024-02-04 03:46 UTC
