### ISSUE TITLE
 Artillery on dropships needs "Ground Dropships Use Individual Weapons" option (Airborne dropship unable to fire arrow IV aritllery)

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#205] opened 2016-05-19 05:20 UTC
Megamek says : Airborne aerospace units can't fire non-Arrow-IV artillery

But the unit is an airborne dropship attempting to fire arrow IV artillery in an artillery bay...

[#battletech.zip](https://github.com/MegaMek/megamek/files/271882/battletech.zip)

**Comment by pheonixstorm** [comment] 2016-05-19 06:38
And what rule says it can still fire? Source and page.

**Comment by Question2** [comment] 2016-05-19 06:45
That's not the point, the error message implies it can since it specifies non-arrow IV artillery.

Arrow IV rules are in tac ops btw.

**Comment by BLOODWOLF333** [comment] 2016-05-20 01:48
p180 TacOps:  ....A unit mounting an Arrow IV (no other artillery weapons may be used to make an airborne attack) may make an artillery attack against ground hexes while airborne; direct-fire airborne artillery attacks cannot be made. When making such an attack, follow all the standard rules for a unit on the ground making an artillery attack, with the following additions. 

.....attacks from Altitude 10 or higher cannot be made.

**Comment by mkerensky** [comment] 2016-05-20 12:56
I was under the impression that airborne units could only use Arrow IV 'bombs' under that rule (though I don't remember why I thought this). Maybe it's the artillery bay triggering the error, not the Arrow IVs it contains...

**Comment by djmbm** [comment] 2016-05-20 12:59
I don't recall the exact rules, but there are definitely rules about airborne artillery. However, that aside, there is also a known issue with the ArtilleryBayWeaponHandler being broken. This is why we say you must use individual dropship weapons when landed option.

**Comment by arlith** [comment] 2016-08-15 00:26
I loaded up the saved game, and this is coming down to ArtilleryBays.  Ultimately, this is a duplicate of [SF [#3766]](https://sourceforge.net/p/megamek/bugs/3766/).

**Comment by HammerGS** [comment] 2016-11-26 00:31
Reopening this is include some information recently receiving from a CGL source.

When asked about how rules would handle this in TT the reply was:

If 4 Long Toms combine to form a bay then damage for the bay would be calculated they these for 20 point damage weapons. So 8 Cap Scale Damage. In situations where a bay attack is used that would be the value.

But if used on a Ground Map treat each weapon as an individual weapon purposes for attack.  So the Bay becomes 4 Long Toms each making its own attack roll.

For reference this bug is the same as here:
https://sourceforge.net/p/megamek/bugs/3766/

I've changed the title here to reference the SF bug and will be closing the SF bug.

**Comment by mkerensky** [comment] 2017-11-01 20:46
This is fixed in PR#734, though it won't work quite right until the unit files are changed to account for the artillery bay errata in Hammer's 11/25/16 post.

**Comment by mkerensky** [comment] 2020-01-23 14:33
Full support for artillery dropships (airborne or grounded) has been implemented. This can be closed.

**Closed** 2020-01-23 14:43 UTC
Labels: Bug, Aerospace, DropShip
