### ISSUE TITLE
VSPL to-hit bonus bug (47.2, windows)

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#1596] opened 2020-01-12 03:15 UTC
Every VSPL laser (small, medium, and large) is now firing with a "-4 weapon to-hit modifier" at every range band in addition to the standard variable to-hit modifier that the weapons should have.

**Comment by HammerGS** [comment] 2020-01-12 03:46
Duplicate of https://github.com/MegaMek/megamek/issues/1546

**Closed by HammerGS** 2020-01-12 03:46 UTC
Labels: Duplicate
