### ISSUE TITLE
RFE Double click unit to open Unit View. 

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#3854] opened 2022-08-13 00:05 UTC
From Discord 

![1E33CB34-2EC2-49F2-BC1D-4D5B9DE04881](https://user-images.githubusercontent.com/13752452/184458460-c42d0f9a-f6c3-4a52-ba90-97621fe0e111.jpeg)

**Comment by kuronekochomusuke** [comment] 2022-11-29 22:10
duplicate of #1307

**Closed by kuronekochomusuke** 2022-11-29 22:10 UTC
Labels: Enhancement, GUI
