### ISSUE TITLE
Depth1 water tiles not loading

### ISSUE THREAD

**Issue by grylock666** [MegaMek/megamek#2954] opened 2021-06-19 12:04 UTC
### Environment
MegaMek from MekHQ Gradle build #1374
Windows
AdoptOpenJDK11

### Description
Depth 1 water tiles are not loading (icon missing?) on any maps since several builds back. Only white tile with red cross through it. Bridges over those tiles get loaded though.

### Files
None provided, shows up on every map with depth 1 water tiles. Again, issue has been active since several builds back.

**Comment by neoancient** [comment] 2021-06-19 12:34
Duplicate of #2917, fixed by #2932

**Closed by neoancient** 2021-06-19 12:34 UTC
Labels: Duplicate
