### ISSUE TITLE
Area of Effect Damage on Buildings

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#28] opened 2016-02-10 02:42 UTC
Note: all testing was done with Artillery Cannons and Homing Arrow IVs.

Area of effect weapons are not dealing the proper amount of damage to buildings or the units within them. For example, a Sniper Cannon shooting at a building currently deals 10 damage to its CF and no damage to any Battle Armor within it. The Battle Armor is also non-targetable, giving the message "Infantry protected by building".

The AoE damage against buildings section of Total Warfare, pages 172-173, states that this scenario should instead see the building take a total of 40 damage to its CF, and any units at the targeted level the standard AoE damage (so 10 damage per suit for BA).

These rules work alongside being able to target a building's specific level, which does not appear to be an option at the moment. Still, this AoE change would be a huge boon for fighting on urban maps.

**Comment by arlith** [comment] 2016-02-12 20:56
This is a duplicate of a ticket that's currently on SF.  https://sourceforge.net/p/megamek/bugs/3878/.  I'm going to close it as such and link to this ticket.

**Closed by arlith** 2016-02-12 20:56 UTC
Labels: duplicate
