### ISSUE TITLE
[0.50.0-SNAPSHOT] Princess attempting impossible shots (firing on 13's)

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/megamek#5928] opened 2024-08-19 17:56 UTC
### Environment
megamek.MegaMek.initializeLogging(MegaMek.java:146) - Starting MegaMek v0.50.0-SNAPSHOT
    Build Date: 2024-08-14T01:19:23.017778387
    Today: 2024-08-19
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 17.0.6
    Platform: Windows 10 10.0 (amd64)
    System Locale: en_US
    Total memory available to MegaMek: 8 GB
    MM Code Revision: 73b326a9d0279583593f95e4a786452171085e4e
    MML Code Revision: fc321e451b068ba6292e43ecc1f6ce80345d79cb
    MHQ Code Revision: 97bfe2272ed3dd97837249f987f8617facdf82ac

### Description
Princess used this crocket and fired her LBX10 two rounds in a row, despite needing a 13 to hit both times. The first time, there was a message about her switching from cluster to slug for "better damage probability" even though with cluster she would only have needed a 12 to hit.

### Files

[FiringOn13s.zip](https://github.com/user-attachments/files/16663680/FiringOn13s.zip)

**Comment by Sleet01** [comment] 2024-08-19 20:24
This may be a dupe of #5590 , or it may be a separate issue.

**Comment by Sleet01** [comment] 2024-12-20 17:42
Getting back into this; it does look like a dupe of #5590 so closing the newer issue in favor of the older one.

**Closed by Sleet01** 2024-12-20 17:42 UTC
Labels: Bug, Princess/AI
