### ISSUE TITLE
MegaMek via MekHQ Predesignated targets

### ISSUE THREAD

**Issue by KiloWhiskey1** [MegaMek/megamek#1575] opened 2019-12-21 00:28 UTC
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment

MekHQ MegaMek 47.2

Windows

Unknown

### Description
Predesignated targets are working not only as an auto hit for arty but also for any weapon fired at them. Both for the hex and for the units in it.

Not something that is game breaking but is an amusing bug.

### Files
Did not save file

**Comment by neoancient** [comment] 2020-01-11 18:29
Duplicate of #1576. Closing this one because the other has more data.

**Closed by neoancient** 2020-01-11 18:29 UTC
Labels: Duplicate

**Comment by KiloWhiskey1** [comment] 2020-01-11 19:37
Rock on. Thanks
