### ISSUE TITLE
RFE: Divider between firing units in round report

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#2616] opened 2021-01-31 18:55 UTC
In the round report, you get a lot of lines of text describing how [x] shoots [y], but it can be hard to spot when [x] changes from one unit to the next if skimming through the report looking for weapons fire from a specific unit. A simple horizontal divider (just a line crossing the screen or similar) between weapons fire from each unit would make this much easier to spot.

**Comment by kuronekochomusuke** [comment] 2022-11-29 21:56
duplicate of #1678

**Closed by kuronekochomusuke** 2022-11-29 21:56 UTC
Labels: Enhancement, GUI, Reports
