### ISSUE TITLE
Princess Fails to Deploy

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/megamek#33] opened 2016-02-19 20:39 UTC
This error keeps on coming up but repeating it is impossible to repeat. IIRC it has been happening since 3.14 at least. Unfortunately, the only way to clear the error is to quit all Java. The only way to repeat the error is NOT to quit all Java.

java.lang.NullPointerException
	at megamek.common.pathfinder.ShortestPathFinder.getLevelDiff(ShortestPathFinder.java:392)
	at megamek.common.pathfinder.ShortestPathFinder$MovePathAStarComparator.compare(ShortestPathFinder.java:212)
	at megamek.common.pathfinder.ShortestPathFinder$MovePathAStarComparator.compare(ShortestPathFinder.java:167)
	at java.util.PriorityQueue.siftUpUsingComparator(Unknown Source)
	at java.util.PriorityQueue.siftUp(Unknown Source)
	at java.util.PriorityQueue.offer(Unknown Source)
	at java.util.PriorityQueue.add(Unknown Source)
	at java.util.AbstractQueue.addAll(Unknown Source)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:298)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:325)
	at megamek.client.bot.BotClient.hasPathToCenter(BotClient.java:820)
	at megamek.client.bot.BotClient.getStartingCoordsArray(BotClient.java:766)
	at megamek.client.bot.princess.Princess.calculateDeployment(Princess.java:247)
	at megamek.client.bot.BotClient.calculateMyTurn(BotClient.java:398)
	at megamek.client.bot.BotClient$CalculateBotTurn.run(BotClient.java:100)
	at java.lang.Thread.run(Unknown Source)

**Comment by arlith** [comment] 2016-02-20 01:21
ShortestPathFinder.getLevelDiff gets the Hex for the current position (Coords) in the passed movepath, but it doesn't check to see if the Hex is non-null.  If the Coords is off the board, the Hex could be null.  I think that this could naturally happen with paths along the edge of the map. I added a null-guard in 4560acc

**Comment by pheonixstorm** [comment] 2016-02-23 09:23
This needs to be reopened. Started a new game, generated map, bot deploys center. Bot NPEs in deployment phase. This was played on a build based off the latest commit.

[mekhqlog.txt](https://github.com/MegaMek/megamek/files/142208/mekhqlog.txt)
[pathnpe.sav.zip](https://github.com/MegaMek/megamek/files/142210/pathnpe.sav.zip)

**Comment by arlith** [comment] 2016-02-23 16:44
Alright.  I was taking a stab in the dark with the last fix.  There are actually two hexes involved: the current position and the goal position.  It didn't seem like the goal could be null, but maybe it is.  Can you reproduce this reliably?  If I load that saved game, do you see it everytime?  If I can reproduce the issue, I can make a more solid fix.

**Comment by pheonixstorm** [comment] 2016-02-23 20:22
This was the first time I have run across this NPE. Using the saved game I could not reproduce but as scJazz said as long as you don't close out of HQ this error shows up every time. Once you close the program it pretty much resets itself and goes away.

If I run across it again I will post another log and save, though this time it will be the autosave which may be easier to reproduce from rather than after the fact.

**Comment by scJazz2** [comment] 2016-02-23 21:52
The error is runtime. As long as the broken state is in effect any game will be broken and Princess will screw up everytime. You can quit that MM, launch another game from MHQ, still broken. 

It only stops being broken when MM and MHQ and (MML ???) have been closed. MHQ restarted, MM begun again. However, if you launch it on your system to reproduce... no issues.

**Comment by arlith** [comment] 2016-03-22 17:07
Is this reproducible reliably using MHQ?  Is this something that happens when you play two subsequent games started from MHQ?  I'm at a bit of a lose as to what's causing this, since I don't see how the destination Coords in this case could be off the board, unless the BotClient has a Game state that is out-of-sync (aka, has the wrong board or something).  Even if I have to load up a cpnx file and start a game in MHQ, I can do that, but I still don't have a clear steps-to-reproduce using MHQ, so I'm basically stabbing in the dark trying to reproduce this issue.

**Comment by scJazz2** [comment] 2016-03-22 17:20
As mentioned earlier... the error is Runtime. Once it starts to happen, launching AtB games from MHQ, it will happen every time there after until MM and MHQ are closed and restarted. I've tried loading a broken save game but that doesn't work. I will send in the full set of files when it happens again although I doubt it will help. Once MM and MHQ are restarted the bug goes away (loading files from a bug report would be the same thing). I will keep looking for any similarities that might allow reproduction.

**Comment by arlith** [comment] 2016-03-22 19:17
I understand what you said before, but still, I want to know if you can reproduce this everytime by loading up MHQ, starting a scenario, then playing another scenario again without restarting MHQ, or if this is an intermittent issue, even if you play multiple MM games within one MHQ session.

I find it surprising that restarting MHQ fixes the issue, as each time a scenario is started, a brand new BotClient is instantiated (`AtBGameThread.run()` line 221).  If the client were getting reused, I might see this.

`BotClient.hasPathToCenter(2)` line 795 could potentially be the culprit.  Basically, the `BotClient` stores the boardCenter `Coords` as a state variable, and only updates the board center on the very first call to `BotClient.hasPathToCenter(2)`.  I cold see that, if the `BotClient` were getting re-used, and you played a second scenario with a significantly smaller board, it would be possible that the board center from the old board would be off the edges of the new board.  However, from what I can see, the `BotClient` isn't reused between games, and the  board shouldn't ever change after the first call to `BotClient.hasPathToCenter(2)`.  However, I also don't see it being necessary to have the board center cached as a state variable.  At best, it could be passed as a third argument to `BotClient.hasPathToCenter(2)`.  However, without being able to reproduce the issue, I can't tell if this will fix it or not.

**Comment by pheonixstorm** [comment] 2016-03-22 19:17
Yeah I haven't run across this NPE since my last post. Is it possible that this has something to do with generated hill/mountain style maps?

**Comment by scJazz2** [comment] 2016-03-22 19:23
The issue is intermittent. It does not occur everytime I load a game from MHQ. Once it does occur, it will keep occuring until I restart MHQ.

**Comment by Akjosch** [comment] 2016-03-31 13:37
What to do to give us a chance at debugging it:

# Make sure you have a full JDK installed. No, a JRE won't do it.
# In the installation directory, there should be Java VisualVM (`bin\jvisualvm.exe` in Windows). If MekHQ/MegaMek do that again, start it.
# In the "Applications" panel on the left side, expand the "Local" tree
# It should have the game (along with every other Java program running). Double-click on the game process to open it.
# Right-click on the game process, pick "Heap Dump". It should appear right under the process in the tree.
# Right-click on the heap dump, pick "Save As ...". Save, compress, upload somewhere we can download from. Those can get *quite* large, so be warned.
# Making a thread dump and application snapshot from there is not strictly required, but can be helpful.
# Make sure to note which exact version you're using when you submit the heap dump!

**Comment by Dylan-M** [comment] 2016-03-31 13:47
@Akjosch You should make a wiki entry for this.

**Comment by arlith** [comment] 2016-03-31 13:50
I also had a forum post on the megamek.info forums with some details about getting a heap dump.

**Comment by pheonixstorm** [comment] 2016-04-01 02:30
I use custom compiles so would probably have to upload that as well

**Comment by Akjosch** [comment] 2016-04-01 07:30
@pheonixstorm That depends. If you changed the data structures, yes. If it's just added/removed/modified methods, no. A heap dump is simply a mirror of all the data structures currently in memory.

**Comment by Akjosch** [comment] 2016-04-01 08:08
@Dylan-M [Wiki entry done](https://github.com/MegaMek/megamek/wiki/Creating-a-Heap-Dump).

**Comment by pheonixstorm** [comment] 2016-04-02 02:18
@Akjosch  My compiles use pretty much everything I find useful such as all my SPA work, hidden units, and anything else I am working on usually.

**Comment by pheonixstorm** [comment] 2016-04-25 06:50
Got a heapdump on this so uploaded it and my custom build to my dropbox account. Hopefully now we can get this bug fixed.
https://www.dropbox.com/s/ghjnlsyygs3o4u2/mekhq-0.3.28-git-windows-2.zip?dl=0
https://www.dropbox.com/s/p4bfafuidp3wuon/heapdump-1461564732927.zip?dl=0

**Comment by pheonixstorm** [comment] 2016-04-26 20:11
@arlith  is there anything else you need? I still have the save if you want me to upload it

**Comment by scJazz2** [comment] 2016-08-03 00:38
@arlith no not anytime lately. Close it for now. If necessary will re-open.

**Comment by HammerGS** [comment] 2016-08-03 00:43
Closing Per OP Request.

**Closed by HammerGS** 2016-08-03 00:43 UTC
Labels: bug
