### ISSUE TITLE
47.14 On-map artillery not allowed to pre-designate autohit hexes when unofficial rule is engaged.

### ISSUE THREAD

**Issue by orcmaul** [MegaMek/megamek#2477] opened 2020-12-04 23:21 UTC
Found in Megamek Windows 0.47.14.

When (Unofficial) Allow artillery units on-map to pre-designate autohit hexes is set to true and an artillery equipped unit is deployed on the map at the start of the game the game does not start with a phase for designating autohit hexes.  Tested with artillery deploying after the start of the game and issue persists.  Off-map artillery working as intended with pre-designating autohit hexes phase.  

Repro:
1: Set (Unofficial) Allow artillery units on-map to pre-designate autohit hexes to true.
2: Add a unit with an artillery piece to your side.  (I tested with Thor artillery vehicle and Sniper artillery vehicle).
3: Start Game.  Game immediately proceeds to deployment phase and regular play continues from there.  The phase for pre-designating autohit hexes never occurs.  

Speculation:
Because the unit is deploying on-map in the deployment phase the preceding pre-designating phase is not being triggered.  Unfortunately, it doesn't happen in subsequent turns either so I guess it's not checking to see if that ever happened.

**Comment by sixlettervariables** [comment] 2020-12-18 18:18
Unofficial rules are at the low end of our support structure, so I've tagged this Help Wanted. It is unlikely any of the core team will get to this in the near future, but we always welcome help!

**Comment by TenkawaBC** [comment] 2021-01-07 22:13
Found the culprit, how to fix is a bit more complex.

server\Server.java
method "endCurrentPhase()"

Line 2767: 
case PHASE_STARTING_SCENARIO is the only place where IGame.Phase.PHASE_SET_ARTYAUTOHITHEXES is set in the entire codebase.

So right now the only time autohit hexes can be set is when starting the scenario. 

The good news is that triggering "changePhase(IGame.Phase.PHASE_SET_ARTYAUTOHITHEXES);" will pop the selection and enumeration screen.

We would need to add some kind of detection of new artillery units and call this changePhase as a result, plus add some logic to prevent re-allocating auto-hit hexes.

I wonder if adding a check at the end of PHASE_DEPLOYMENT would work, as that would only trigger when deploying units.

**Comment by neoancient** [comment] 2021-01-07 22:18
The problem is in Entity::isEligibleFor(IGame.Phase). The first statement returns false for any unit that's not deployed if it's not the deployment phase. Offboard artillery is considered deployed, so it gets to be eligible for PHASE_SET_ARTYAUTOHEXES.

**Comment by neoancient** [comment] 2021-01-07 22:21
PHASE_STARTING_SCENARIO is only used for scenarios and is not used for regular games.

**Comment by TenkawaBC** [comment] 2021-01-07 23:30
Thanks Neoancient. I've been digging further at it, but good to know.

**Comment by TenkawaBC** [comment] 2021-01-08 19:03
Branch created and pull request submitted with potential fix.

**Comment by Windchild292** [comment] 2022-01-29 18:23
Fixed in #2558

**Closed by Windchild292** 2022-01-29 18:23 UTC
Labels: Bug, Help Wanted, Unofficial
