### ISSUE TITLE
GAC Ammo Variant Do Not Respect Tech Level Cap

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#1059] opened 2018-07-22 17:14 UTC
### Environment
Occurs in MM and MML 0.44.0
Java 1.8
Windows 8.1

### Description
Tech level is set to standard but the various GAC ammo variants are showing as available when they should be unofficial tech.  The standard GAC ammo is behaving correctly.

![image](https://user-images.githubusercontent.com/16950832/43048171-bd73eef6-8da8-11e8-8f67-44e4d44eaedd.png)

![image](https://user-images.githubusercontent.com/16950832/43048173-caa39a86-8da8-11e8-9947-3c6ea155ab87.png)

### Files
NA

**Comment by neoancient** [comment] 2018-07-22 17:35
Duplicate of #1017

**Closed by neoancient** 2018-07-22 17:35 UTC
Labels: Duplicate
