### ISSUE TITLE
Flak AC ammo doing 1/2 damage, rounded up

### ISSUE THREAD

**Issue by TigerShark** [MegaMek/megamek#359] opened 2016-10-11 04:20 UTC
Per TW, isn't flak supposed to do full damage to Aero / VTOL?

[autosave_2016-10-10_21-00-23.sav.gz](https://github.com/MegaMek/megamek/files/520962/autosave_2016-10-10_21-00-23.sav.gz)

**Comment by arlith** [comment] 2016-10-24 20:24
Pretty sure this is correct, per errata.  I'm not 100% certain without checking on the rules.  Looks like someone answered your question when you asked here: http://www.mekwars.org/forum/viewtopic.php?f=2&t=9078.  Pretty sure this is working as intended and I'm going to close this.  If it's not, you can update the ticket and we can look into it.

**Closed by arlith** 2016-10-24 20:24 UTC
Labels: bug
