### ISSUE TITLE
[0.41.19 : Bug] BoardView1.drawHex NPE

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#272] opened 2016-07-08 08:31 UTC
Custom atmospheric.tileset file causing BoardView1.drawHex NPE in 0.41.19 Map Editor, but is working fine in 0.41.17.

Atmospheric.tileset file was edited from 0.3.29/0.41.19 download. When trying to open A Test Set 2 - 34 x 35.board from 0.41.19 map editor, I will either get the BoardView1.drawHex NPE (and frozen) or the board will not get loaded properly.

When tested on 0.3.27/0.41.17 map editor using the same tileset, board and custom images, everything was loaded without any problem.

[BoardView1.drawHexLog.txt](https://github.com/MegaMek/megamek/files/353778/BoardView1.drawHexLog.txt)

[SirMegaVHexes.7z.txt](https://github.com/MegaMek/megamek/files/353779/SirMegaVHexes.7z.txt)

[A Test Set 2 - 34 x 35.board.txt](https://github.com/MegaMek/megamek/files/353784/A.Test.Set.2.-.34.x.35.board.txt)

**Comment by BLOODWOLF333** [comment] 2016-07-24 17:44
I have been able to reproduce this issue many times in a row today in the board editor while trying to create a snow theme for the normal atmospheric tilest that would use the already included images for snow trees and roughs but, cannot because of this drawing error :(.

mm0

Was at first getting that parsing error with the skin file after reinstalling Java 8 101 but, finally fixed it and still am not sure why the skin parsing error occurred?

What seems to be causing it is if you attempt to use a theme like "grass, snow, lunar, etc" it will mess up like in the above picture but, if I then generate a new board and clear out the theme text box it will redraw fine.

MM board editor generate a new map with no theme and should draw correctly.
Now click new and generate a new map with any theme typed into the text box and will receive errors.
megameklog.txt

**Comment by arlith** [comment] 2016-07-25 18:26
I'm going to close this issue as a duplicate of #284.  The information in this ticket is valid and useful, but it's referenced in the other issue, and i'd like to try to centralize discussion on this problem.

**Closed by arlith** 2016-07-25 18:26 UTC
