### ISSUE TITLE
BattleMaster BLR-1GHE missing from unit selection for IS TW Non-Box Set 0.49.8

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#3778] opened 2022-07-11 14:04 UTC
The BattleMaster BLR-1GHE is missing from the unit selection for IS TW Non-Box Set.  Per the MUL it's considered "Standard" rules level.

![image](https://user-images.githubusercontent.com/18338059/178282301-8725390b-98d8-4dfe-8dfc-80de6cfd25e0.png)

![image](https://user-images.githubusercontent.com/18338059/178282530-abfa27d7-62a5-409b-a71e-743efe0a8158.png)

**Comment by HammerGS** [comment] 2022-07-13 03:43
Duplicate of #3779

**Closed by HammerGS** 2022-07-13 03:43 UTC
