### ISSUE TITLE
Bug: 49.6 Aerotega takes half damage from ranged damage for no reason

### ISSUE THREAD

**Issue by MarcJC** [MegaMek/megamek#3438] opened 2022-02-09 18:38 UTC
Using 49.6 playing a regular MegaMek game and I noticed on the round report that my Aerotegas (there are two) were taking half damage from all ranged attacks.  Both energy, ballistic, and missile weapons seemed to do half damage to these mechs for no decernable reason.  Falling damage however seemed to do normal damage to the mech.    

Also in the game there were some incorrect pathing issues.  Where attempting to move in a straight line cause weird detours, these were not related to elevation issues as it occurred with jump movement also.   
In addition there was an interesting edge case where a mech standing in a -7 height hole with 6 jump jets and a partial wing for 8 total jump movement could not jump directly to a -1 height hex because of a pathing issue, but was able to jump to a +1 height hex in it's range.  This seems odd because I am unsure if the number of heights a mech can jump up is limited to the number of jump jets it mounts, or if any increases to jump movement (aka partial wing) increases jump height.  My understanding of the partial wing is it allows gliding so the distance a mech can jump is longer, but would not raise the height that a mech could jump to, as it provides no additional thrust.  However for a TW ruleset it may simply be abstracted.  

Attached are the logs a savegame and the customs folder even though I do not believe any customs are in use for this game 

Let me know if there are any other files or data needed for this issue.
[game bugs.zip](https://github.com/MegaMek/megamek/files/8035327/game.bugs.zip)

**Comment by MarcJC** [comment] 2022-02-09 18:45
Just remembered there was another weird issue that occurred on this game.  A mech tried to TAG an enemy mech but missed the hit roll, and the target was not tagged.  However later in that round a third mech using a MML 5 loaded with semi-guided LRMs and set to indirect was able to target the mech that I had attempted to TAG with no one else spotting.  It however did not get any bonuses for the semi-guided ammo since the target was not tagged.  Other mechs in range that it attempted to target with that system received the no available spotter message.

**Comment by repligator** [comment] 2024-07-17 00:36
Could you please clarify what an Aerotega is? I can't find them in the customs folder you posted.

**Comment by gsparks3** [comment] 2024-07-17 00:56
Might be a typo for Agrotera?

**Comment by repligator** [comment] 2024-07-17 01:23
> Might be a typo for Agrotera?

Thanks. I knew that sounded familiar...

**Comment by repligator** [comment] 2024-07-17 13:28
Based on the logs, there is definitely something funny going on. For starters, the Total memory available to MegaMek is 2,147,483,648 GB.

The gamelog.html is interesting. The Agroteras get very lucky with glancing blows, (which legitimately reduce damage by half). But then they start taking clean hits from ERPPCs and Gauss Rifles that are _not_ glancing blows, but are doing exactly half damage (rounded down).
![Screenshot 2024-07-17 at 09-06-25 ](https://github.com/user-attachments/assets/8baa8966-0238-41de-b08c-59425bcdf41b)

**Comment by MarcJC** [comment] 2024-07-17 18:34
Apologies on the typo.  

If this the issue I think it is, been a while,  I think the half damage occurred because the mech was standing on (or in) a specialized building (id type 2 or 3 not sure) that is 1 height and intended to have a gun turret on it that takes half damage, and only infantry can enter it.  

I think I tried to have the mech enter the building using the climb button but was surprised to find out my mech was on top of the building.  I had chalked that up to user error, but later found out via the discord about the building type and the inability of any unit other than infantry to enter them.  
It does seem that in some way either the mech entered the building while being on top of it, or was somehow converted to being a gun turret on top of the building and was using the building's effect that gun turrets on top of it took half damage from being hardened.    I believe I tried to replicate the issue using the building again with other mechs and other buildings of that type on the map.  Hey half damage is half damage and Princess doesn't complain.  I think I was unable to cause the effect to occur again.  Likely because I wasn't playing with the climb button to try to enter the buildings again but I am not sure.  
Those are my guesses to how this occurred.  I wouldn't be surprised to find out a race condition might be involved probably connected to the climb button.  This bug is gonna be a hard one to track down as it is not easily replicated.  Luckily it should be very rare considering all the things that need to occur to cause it, so most players will be unlikely to ever encounter it.  
As for the memory, I don't normally mess with those settings so I have no idea why the log would report such altered memory values.
Good luck with this one.   

    On Wednesday, July 17, 2024 at 09:28:43 AM EDT, Holovis ***@***.***> wrote:  
 
 


Based on the logs, there is definitely something funny going on. For starters, the Total memory available to MegaMek is 2,147,483,648 GB.

The gamelog.html is interesting. The Agroteras get very lucky with glancing blows, (which legitimately reduce damage by half). But then they start taking clean hits from ERPPCs and Gauss Rifles that are not glancing blows, but are doing exactly half damage (rounded down).
Screenshot.2024-07-17.at.09-06-25.png (view on web)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
  

|  | Virus-free.www.avast.com |

**Comment by gsparks3** [comment] 2024-07-17 21:00
Ah, yes, if there was a Fortress or Gun Emplacement on the field, and the mechs were in the hex of such a building, this would be a (much earlier) duplicate of #4425. Not yet fixed, but the later report is sufficient and more directly addresses the issue.

**Closed by gsparks3** 2024-07-17 21:00 UTC
Labels: Bug
