### ISSUE TITLE
[0.41.19 : Error] VTOL Elevation not Reset Between Games

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#257] opened 2016-06-17 09:08 UTC
As per title, VTOL elevation not reset between games.

**Comment by pheonixstorm** [comment] 2016-06-17 18:56
Is this from a HQ game or saving a MUL at the end of MM and reusing it for the next MM session?

**Comment by arlith** [comment] 2016-06-17 20:16
I was assuming it was a MHQ bug.  If it's related to a MUL file, it's working as intended: the MUL file should encode the elevation, to make it easier to setup a game.

**Comment by pheonixstorm** [comment] 2016-06-18 00:09
If it is from HQ (most likely) It wouldn't be hard to fix though will have to test it. Don't recall what the default is.. I think 2

**Comment by SirMegaV** [comment] 2016-06-18 00:35
Both games started from MHQ. Issue posted at the wrong place?

**Comment by arlith** [comment] 2016-07-28 20:05
This is really a MHQ bug, but I have fixed with with MegaMek/mekhq@faf0560  (originally MegaMek/mekhq@0bb087fa3ce35af9b325b50f88929438e51de0ef, but that was a mistake).  `Campaign.clearGameData` wasn't resetting elevation, which it probably should (although really this only matters for VTOLs and WiGEs).  The problem is, it wasn't exactly clear what to reset it as.  Initially I thought it needed to be 0 for everything but VTOLs, which should be 1.   Turns out, basically everything should be 0 (which represents standing on top of a hex).  If VTOLs have a 0 elevation, then the deployment display will set their elevation to 1 when they deploy, otherwise if they have a non-zero elevation it assumes the elevation was set in the lobby.

**Closed** 2016-07-28 20:05 UTC
Labels: bug
