### ISSUE TITLE
Board does not display if skin does not have BoardView with a background image

### ISSUE THREAD

**Issue by ObviousTech** [MegaMek/megamek#329] opened 2016-09-06 02:13 UTC
v0.41.22
Using plainSkin.xml.

The board will not display. Many NPEs in the log from trying to draw it:
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at megamek.client.ui.swing.boardview.BoardView1.paintComponent(BoardView1.java:1144)

In the skin editor, added a BoardView element to plainSkin.  Still does not display the board in Megamek.
Added a background image to that BoardView. Megamek now displays the board correctly.

**Comment by BLOODWOLF333** [comment] 2016-09-06 03:14
Deletes plainskin and with scroll bars on my copy now.  Much better

**Comment by arlith** [comment] 2016-09-10 13:58
This issue was inadvertently fixed in 5055ff.

**Closed** 2016-09-10 13:59 UTC
Labels: bug

**Comment by wildj79** [comment] 2016-09-10 15:54
@arlith Inadvertently? Your gonna have to explain that 😉

**Comment by arlith** [comment] 2016-09-10 17:08
The NPE was caused by this code:

```
if ((bvBgBuffer == null) && (bvBgImage != null)
                || (bvBgBuffer.getWidth() != viewRect.getWidth())
```

I refactored out the `bvBgBuffer` variable in 5055ff3.  I didn't know this bug existed, and I wasn't trying to fix it, I was instead trying to fix another bug.
