### ISSUE TITLE
Tree problem/bug

### ISSUE THREAD

**Issue by BrownAdept** [MegaMek/megamek#610] opened 2017-08-29 19:39 UTC
Trees need a lot of work as to sighting through them and changes to the to-hit number. In BT, heavy woods count as 2 and light woods as 1 point for sighting, with 3 points being (supposedly) the max and then only if seeing INTO the third point of woods.  

I've observed, in Megamek, that woods do NOT matter for sighting at all.  Second, heavy woods SHOULD add +2 to being hit and light woods a +1, into or through them.  This is also NOT reflected in Megamek.  These errors make tactics and maneuver VERY difficult.  

**Developer Edit** - Moved Hull Down reference to - https://github.com/MegaMek/megamek/issues/616

**Comment by pheonixstorm** [comment] 2017-08-29 19:42
Unless something recently broke trees have worked for awhile. Also, the issue you list with hull down should be its own ticket.

**Comment by NickAragua** [comment] 2017-08-29 19:44
It would be very helpful to have a saved game (and even more helpful with units pointed out where tree LOS isn't working as intended). Same with the hull-down issue, although as pheonixstorm points out, that should be a separate ticket.

**Comment by HammerGS** [comment] 2017-08-30 01:54
I haven't seen issues with trees or forest in ages.  What version is being used.

**Comment by BrownAdept** [comment] 2017-08-30 16:06
Greetings,


Thanks for a reply.  I assume this is the current version as there are about 10+ gamers at the Megamek site gaming regularly.  More come and go.


Bobb


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by BrownAdept** [comment] 2017-08-30 16:08
Greetings,


Thanks for the reply.  I'll try to save the next game and forward it to you.


Bobb


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by BrownAdept** [comment] 2017-08-30 16:16
Greetings,


     Thanks for the reply.  I was observer yesterday at a game specifically because I'd noted the problem in my own gaming.  I specifically watched an archer observe and shoot through 4 light woods hexes.  In my own games, I walk +1, and shoot at range +4, at two targets that moved 5 = +2.  Both are 7 to hit even though one is now in heavy woods. Ssssoooo, no I don't think woods are correct.


Bobb


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by NickAragua** [comment] 2017-08-30 16:55
While, I appreciate the description, we are not going to be able to troubleshoot a problem without a saved game where it's clearly occurring. So next time you see it, save the game, then attach the saved game to this issue, along with a clear indication of which units you think have incorrect modifiers.

**Comment by pheonixstorm** [comment] 2017-08-30 23:44
Sounds like they could be counting the woods the attacker is in?

**Comment by BrownAdept** [comment] 2017-08-31 16:12
Greetings,


I have no idea why anyone would count the attackers location into hit probability.  Not in the normal rules I'm familiar with.


Bobb


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by BrownAdept** [comment] 2017-08-31 16:13
Tks.  Will try.


Bobb


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by HammerGS** [comment] 2017-08-31 18:21
In the attached Album you can see the various type of LOS and to hits and they all include the correct modifiers and LOS blocks. What this example doesn't show is if Double Blind is one.

http://imgur.com/a/iHyTU

**Comment by BrownAdept** [comment] 2017-09-01 17:43
Greetings,


     I praise you for your response.  I note here that light woods and heavy DO affect the to=hit number.  What I have not seen, in the Megamek game, is the written to-hit math line, e.g. +4 range,+1 firer walked, +2 target moved 6 hexes, +1 FOR WOODS, +1 for hull down, that you're pics show.  I've also not noted it when I do the math myself during firing.  I shall look again for the math line.

     I assume that the special sighting shown in your pics is due to special equipment, of which I am unfamiliar.  This is, of course, my own ignorance.

     I'm only an occasional gamer with no connection with this games construction.  It's only been my wish to bring what I saw as an oversight to someones attention, in an effort to help.  I can game on, or not, in any event and I thank the designers for their effort.


Bobb


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by HammerGS** [comment] 2017-09-03 21:07
Closing this as working.

**Closed by HammerGS** 2017-09-03 21:07 UTC
Labels: invalid
