### ISSUE TITLE
Bug in megamek 49.15, King david light gauss rifle not doing 1d6 damage when advanced rule battle armor v.s. battle armor damage is turned on

### ISSUE THREAD

**Issue by RexRawhide** [MegaMek/megamek#4874] opened 2023-11-04 22:27 UTC
### Environment
Megamek 49.15 (bug also appears in all the way back to 49.12, I dont have any earlier versions)
Windows 10 home version 22H2
Java version "11.0.12"

### Description
begin game with 3 units on each side, each armed with king david light gauss rifles, and having the tacops battlearmor vs battlearmor damage rule turned on which should make the king david do 1D6 damage when it hits (Tac ops advanced rules page 107).
![image](https://github.com/MegaMek/megamek/assets/149908439/d836a6ff-8cd2-4dc0-a74c-2091f17f41a3)
![image](https://github.com/MegaMek/megamek/assets/149908439/ed415341-c970-4c6e-8bb6-2d622c3c2097)

get into a game and deploy next to AI, then shoot david gauss in shooting phase, when I get to damage screen all units have taken 1 damage.
![image](https://github.com/MegaMek/megamek/assets/149908439/d1784d7f-7da9-4614-85c5-4a221fcdba61)
![image](https://github.com/MegaMek/megamek/assets/149908439/722a4e51-24b1-4058-8f64-44a82f7b4132)
![image](https://github.com/MegaMek/megamek/assets/149908439/07123700-b482-4259-86c0-80d68d6017f2)
![image](https://github.com/MegaMek/megamek/assets/149908439/c5495334-31e0-4e0e-bd30-c7da681a2685)

I have tested other weapons that should be affected by this rule (man portable plasma and bearhunter) and both of those weapons seem to work fine so looks like the problem is specific to the king david.  I should note that I made a rules file on an older version of megamek with all the optional rules I like turned on so that could be having an effect but I'm not sure.

### Files
saved game before shooting
[Bug.sav.gz](https://github.com/MegaMek/megamek/files/13257871/Bug.sav.gz)
megamek log
[bug testing file submission.txt](https://github.com/MegaMek/megamek/files/13257878/bug.testing.file.submission.txt)
Player name
Rex Rawhide

**Comment by SuperStucco** [comment] 2023-11-05 19:20
Stupid question time: are you testing the David Light Gauss, or the King David Light Gauss?  The Leonidas BA is carrying the former, while the latter is the one listed in the TacOps table.

**Comment by HammerGS** [comment] 2023-11-06 00:33
Just tested this and I think the issue is the weapon isn't the King David.
![image](https://github.com/MegaMek/megamek/assets/13752452/1fbe41bc-a184-44ed-8584-260e1a2879ee)

Closing based on testing.

**Closed by HammerGS** 2023-11-06 00:33 UTC
