### ISSUE TITLE
49.9 Crash at the end of fire phase (NPE - Board.isLegalDeployment) and (Java.lang.IllegalStateException)

### ISSUE THREAD

**Issue by BigFluffy10000** [MegaMek/megamek#3883] opened 2022-09-08 02:12 UTC
### Environment
49.9 on Win 11, Java 11 on Asurion

### Description
Game freezing during end of firing phase. 

### Files
[megamek.log](https://github.com/MegaMek/megamek/files/9522984/megamek.log)
![MM Crash Screenshot 2022-09-07 220248](https://user-images.githubusercontent.com/113077172/189018146-0f7c36a1-1901-4c87-a748-35067a2f901c.png)

Also looks like it might have run out of memory.

**Comment by BigFluffy10000** [comment] 2022-09-08 02:40
[NH Test30760622.cpnx.gz](https://github.com/MegaMek/megamek/files/9523135/NH.Test30760622.cpnx.gz)

**Comment by Membooo** [comment] 2022-09-08 13:04
Same Issue here:

Windows 11Home 64 Bit
OPEN JDK Eclipse Temurin with Hotspot 11.0.15+10(x64)
 
exact Same error as described

**Comment by HammerGS** [comment] 2022-09-08 19:52
Reviewing the log we also have these issues.

```
21:12:21,137 ERROR [megamek.client.ui.swing.minimap.Minimap$2] {AWT-EventQueue-0}
megamek.client.ui.swing.minimap.Minimap$2.run(Minimap.java:457) - 
java.lang.NullPointerException
	at megamek.common.Board.isLegalDeployment(Board.java:832)
	at megamek.client.ui.swing.minimap.Minimap.drawDeploymentZone(Minimap.java:592)
	at megamek.client.ui.swing.minimap.Minimap.drawMap(Minimap.java:539)
	at megamek.client.ui.swing.minimap.Minimap.drawMap(Minimap.java:473)
	at megamek.client.ui.swing.minimap.Minimap$2.run(Minimap.java:447)

```

LOTS of these.
```
21:22:27,328 ERROR [megamek.common.pathfinder.LongestPathFinder.LongestPathRelaxer] {Princess-precognition (Free Worlds League Allied Tank Reinforcements)}
megamek.common.pathfinder.LongestPathFinder$LongestPathRelaxer.doRelax(LongestPathFinder.java:170) - Top Move Path uses more MPs than Move Path Candidate.
java.lang.IllegalStateException
	at megamek.common.pathfinder.LongestPathFinder$LongestPathRelaxer.doRelax(LongestPathFinder.java:170)
	at megamek.common.pathfinder.LongestPathFinder$LongestPathRelaxer.doRelax(LongestPathFinder.java:125)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:266)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:295)
```

**Comment by NickAragua** [comment] 2022-09-09 02:13
We're going to need megamek save for this one.

**Comment by BigFluffy10000** [comment] 2022-09-09 06:20
I uploaded the save yesterday under the original post

**Comment by BigFluffy10000** [comment] 2022-09-09 06:21
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/9532826/autosave.sav.gz)

**Comment by HammerGS** [comment] 2022-09-09 14:27
Unfortunately the autosave looks like it from the end of a game.

**Comment by TenkawaBC** [comment] 2022-09-09 15:21
Same problem.

Reproducable every time at the end of the first firing phase. I have repeated it 4 times with the same game.

Here is the beginning of game autosave (before the error)

[autosave.sav.gz](https://github.com/MegaMek/megamek/files/9536652/autosave.sav.gz)

Uncaught java.lang.StringIndexOutofBoundsException detected.

Here is the log:

[megamek.log](https://github.com/MegaMek/megamek/files/9536677/megamek.log)

And the final save after error:

[aftererror.sav.gz](https://github.com/MegaMek/megamek/files/9536683/aftererror.sav.gz)

**Comment by AfroSamurai34** [comment] 2022-09-09 20:17
Java Version: 11.0.15
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 6 GB

![Screenshot (11)](https://user-images.githubusercontent.com/14045991/189434754-8d02d00d-4165-46d1-a5e1-a4101947452d.png)

[megamek.log](https://github.com/MegaMek/megamek/files/9538366/megamek.log)

[mekhq.log](https://github.com/MegaMek/megamek/files/9538374/mekhq.log)

[Kumar's Kommandoes30610722.cpnx.gz](https://github.com/MegaMek/megamek/files/9538382/Kumar.s.Kommandoes30610722.cpnx.gz)


Ran for iterations on the save that HammerGS submitted a (now closed) bug report for me for.  3 of them failed on the first firing phase, the fourth failed on the 3rd firing phase.  

rebooted, loaded up some different units, GM'd some precision ammo on a hovertank to "full" ammuniton status, and started up....the above are the results.  Hope this helps, guys.

**Comment by NickAragua** [comment] 2022-09-11 02:53
PR opened with fix; the ordnance name issue appears to have been addressed by Neo's latest pull request, but it looks like that PR wasn't fully incorporated into the release somehow.

**Closed** 2022-09-11 03:24 UTC
Labels: Bug
