### ISSUE TITLE
Laser Pulse Module causing loading exception. 

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#6135] opened 2024-10-22 15:34 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

Building a unit using the Laser Pulse Module on load in MML via IDEA this is tossed into the log.  Can't sure the unit file but DM me on Discord and I can provide if a developer. 

```
megamek.common.loaders.EntityLoadingException: Unable to match RISC Laser Pulse Module to laser <redacted>
	at megamek.common.MekFileParser.postLoadInit(MekFileParser.java:320)
	at megamek.common.MekFileParser.parse(MekFileParser.java:215)
	at megamek.common.MekFileParser.<init>(MekFileParser.java:69)
	at megamek.common.MekFileParser.<init>(MekFileParser.java:62)
	at megamek.common.MekSummaryCache.loadMeksFromDirectory(MekSummaryCache.java:790)
	at megamek.common.MekSummaryCache.loadMeksFromDirectory(MekSummaryCache.java:775)
	at megamek.common.MekSummaryCache.loadMeksFromDirectory(MekSummaryCache.java:775)
	at megamek.common.MekSummaryCache.checkForChanges(MekSummaryCache.java:270)
	at megamek.common.MekSummaryCache.loadMekData(MekSummaryCache.java:243)
	at megamek.common.MekSummaryCache.lambda$getInstance$0(MekSummaryCache.java:85)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

### Operating System *

Windows 11

### Java Version *

Java 17

### MegaMek Suite Version *

Free Text (type manually)

### Custom MegaMek Version

Build Date: 2024-10-22T08:50:56.841241900

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by SJuliez** [comment] 2024-10-31 08:18
I can't reproduce this. Also, validation for the LPM in MML seems to work well. Therefore closing this until the issue resurfaces

**Closed by SJuliez** 2024-10-31 08:18 UTC
Labels: Bug, Severity: Medium
