### ISSUE TITLE
47.2 Aero LOS Bug

### ISSUE THREAD

**Issue by Mekslayer** [MegaMek/megamek#1671] opened 2020-02-14 02:14 UTC
See Photo attached. It should explain all.

![LOS_Bug_For_Aero](https://user-images.githubusercontent.com/25534324/74495345-772c4780-4e8c-11ea-8508-bc35b35ccf94.jpg)

### Environment
What operating system are you using?  Windows, Mac, or Linux?
Win 10
What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file.

Java version 1.8.0_241

Here is my save from a later turn.

[Holdout-M2_T20_Bot.sav.gz](https://github.com/MegaMek/mekhq/files/4202333/Holdout-M2_T20_Bot.sav.gz)

[megameklog.txt](https://github.com/MegaMek/mekhq/files/4202336/megameklog.txt)

**Comment by mkerensky** [comment] 2020-04-01 15:33
That looks like it is working as intended with Double Blind in play.  Per errata,  Aerospace units can only visually spot ground units that they fly directly over. When using sensors, they can reveal units 1-3 hexes from the flight path (1-6 with an active probe). 
Aeros can spot other airborne Aeros at longer distances.

**Comment by Windchild292** [comment] 2020-10-01 21:11
Closing based on @mkerensky's message.

**Closed by Windchild292** 2020-10-01 21:11 UTC
Labels: Aerospace, Bug
