### ISSUE TITLE
Losing gun emplacement deployment turns with vehicle lance movement on

### ISSUE THREAD

**Issue by AaronGullickson** [MegaMek/megamek#5316] opened 2024-04-05 13:52 UTC
If you have gun emplacements that need to be deployed and you have the vehicle lance movement option turned on, you will not be given enough turns to deploy all gun emplacements. In fact you will only be given a number of turns equal to the correct amount divided by the number of vehicles that move together in vehicle lance movement (rounded down). 

This bug is easy to replicate. Load up a force consisting of four turrets and a map where they can be placed. Set vehicle lance movement to 2. You will only be able to place two turrets and then the deployment round will end.

It seems clear that turrets are being treated as vees for purposes of the number of deployment turns but they are not being treated as vees in terms of being able to deploy X units per turn. IIRC they are a subclass of vee, so likely somewhere a `!(en instanceof GunEmplacement)` is either missing or needs to be added.

**Comment by AaronGullickson** [comment] 2024-04-05 13:52
This is likely the same bug as #4453 but is not a bot issue - it affects human players too.

**Comment by gsparks3** [comment] 2024-04-05 21:30
Duplicate of #3306 (although it's been enough versions since that was reported that knowing it's still active is useful).

**Comment by AaronGullickson** [comment] 2024-04-05 21:35
Whoops, missed that one in my search.

**Closed** 2024-04-06 00:32 UTC
Labels: Bug
