### ISSUE TITLE
[SPA] Oblique Attacker

### ISSUE THREAD

**Issue by Tecmes** [MegaMek/megamek#5497] opened 2024-05-21 21:05 UTC
0.49.19

This SPA is buggy. 
When setting a weapon to Indirect, it not only allows firing on units within LOS, but it also removes cover penalties from the shooter, does not take into account spotter movement or cover (regardless of whether you're firing at a target in LOS or truly indirect). It's like the best of both worlds. You do get the -1 for indirect fire, but you still have the +1 from the SPA...

Setting the weapon to direct yields normal results.

I was wondering why that unit was getting such great indirect shot THs!

**Comment by Gribbly1** [comment] 2024-05-21 21:22
> does not take into account spotter movement or cover

With Oblique Attacker there is no spotter.

**Comment by Tecmes** [comment] 2024-05-21 21:49
Oh, oops, thanks. I don't have AToW, and the tooltip for the SPA only says you don't get the -1.
However, should setting the weapon to Indirect really remove cover penalties from the firer - considering you normally get those from the spotter!?

**Comment by gsparks3** [comment] 2024-05-21 22:39
Intervening terrain for indirect fire is calculated relative to the spotter, so if there's no spotter, there's no intervening terrain.

Yes this is an incredibly busted SPA, why do you ask?

**Comment by Tecmes** [comment] 2024-05-21 23:01
Ah! Makes perfect sense, in its own twisted way... Too bad the SPA rule as written in the tooltip (just no -1) is not actually used, as it's better, more balanced than the actual one!
This solves the "issue", but we might want to keep this thread if other people encounter the same issue (to wit, not having AToW).

**Comment by IllianiCBT** [comment] 2024-05-21 23:15
> Ah! Makes perfect sense, in its own twisted way... Too bad the SPA rule as written in the tooltip (just no -1) is not actually used, as it's better, more balanced than the actual one! This solves the "issue", but we might want to keep this thread if other people encounter the same issue (to wit, not having AToW).

I'm going to close this as working as intended. The 'thread' will persist in GitHub so no worries there

**Closed by IllianiCBT** 2024-05-21 23:15 UTC
Labels: SPA (Special Pilot Abilities)

**Comment by gsparks3** [comment] 2024-05-21 23:17
For further reference, SPAs can also be found in new-printing Campaign Operations.
