### ISSUE TITLE
[49.0] DFA and charging doesn't always work.

### ISSUE THREAD

**Issue by Gantolandon** [MegaMek/megamek#2839] opened 2021-05-06 19:50 UTC
### Environment
Both MegaMek and MekHQ (49.0), Windows, Java 11.0.10

### Description
When you perform a charge or DFA, you get an error similar to this one:
```
20:40:59,204 INFO [megamek.server.Server] {Packet Pump} 
processMovement(), line 7456 : Illegal charge!! Griffin GRF-1N (Black Company) is attempting to charge a null target!
```
The charge or DFA is not performed in the Physical Attack phase. You can no longer continue the game, as the phase will not finish and every action button will be grayed out.

**Comment by NickAragua** [comment] 2021-05-06 20:08
Duplicate of #2757

**Closed by NickAragua** 2021-05-06 20:08 UTC

**Comment by Gantolandon** [comment] 2021-05-06 21:16
Are you sure this is a duplicate? I was able to perform a DFA in 48.0. In 49.0 my every attempt fails.

**Comment by NickAragua** [comment] 2021-05-06 21:23
49.0 has a bug introduced into it which broke DFAs and charges entirely. The issue with charges/DFAs picking up a null target has been around for a while, but has been very difficult to track down.

I'd insert the standard shpiel about save games and log files, but usually when you save and reload to before attempting the DFA (aka at least the beginning of the move phase before the DFA is declared) it tends to disappear.
