### ISSUE TITLE
49.20 MM Standalone Build - NPE Freeze.  Kicking and Replacing Bots does not restart action.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/megamek#5417] opened 2024-04-25 05:02 UTC
Using this specific build https://github.com/MegaMek/megamek/actions/runs/8825771894

was doing bot v bot tests to test the new ammo code.  Twice got an NPE that effectively ended the game.  Froze action.  Tried to kick and replace bots.  No joy.  Had to close.  Was able to load autosave and proceed for a few more turns, but it froze again.  The map is 2x3 Rolling Hills 2. No water on the map at all. 

![image](https://github.com/MegaMek/megamek/assets/23645569/15239cab-6689-4d76-a0b4-fc42c9a55a1a)

A save and log attached.  Was the same error message both times in log. 
 
[megamek - Copy.log](https://github.com/MegaMek/megamek/files/15104412/megamek.-.Copy.log)
[Round-7-autosave_2024-04-24_22-47-29.sav.gz](https://github.com/MegaMek/megamek/files/15104414/Round-7-autosave_2024-04-24_22-47-29.sav.gz)
[Customs41424.zip](https://github.com/MegaMek/megamek/files/15104422/Customs41424.zip)

**Comment by Thom293** [comment] 2024-04-25 05:41
Unsure if related, but these are Brawler mechs set on Berserker v2.  They should be heading straight at the enemy.  No double blind or anything on.

Instead they are hanging at back of map a milling around, like they cant see the enemy or something, but there is no weather or other conditions to prevent vision.  This save is the lobby.  Should work with customs above.  Can set them all to Berserk v2 and hit done and it should repeat.

![image](https://github.com/MegaMek/megamek/assets/23645569/3a9c9ee0-f6d0-410b-9cab-028f6c9f6f5c)
[AMMOTEST1AUTO.sav.gz](https://github.com/MegaMek/megamek/files/15104774/AMMOTEST1AUTO.sav.gz)

**Comment by HoneySkull** [comment] 2024-04-26 03:09
![image](https://github.com/MegaMek/megamek/assets/83041327/240fdca4-e0c4-495e-b710-d0d2b6107f14)

Hit this in a story arch game against the bot using the code from the .20-snapshot on 2024.04.25.

**Comment by Thom293** [comment] 2024-04-26 03:14
Ive run about 20 games on this build now and it has happened in all but one that ended on round 9 due to some lucky crits.  Had it happen on the rest of them though.

You can workaround by loading an autosave and it will continue, but will eventually hit the NPE again.

**Comment by HoneySkull** [comment] 2024-04-26 03:16
NOTE: The NPE I logged above is with a build that include the merge from #5418.

**Comment by HoneySkull** [comment] 2024-04-27 17:25
![image](https://github.com/MegaMek/megamek/assets/83041327/13b376ed-67d1-45e3-a331-d3ebc9335a41)

Put in some debug code to look at the `MovePath` when this happens.  Looks like it's going off the board??  
Hopefully I can get some more samples.

This can be fixed by doing some null checks in this code -but I'm more interested in how this null coordinate condition can come to be.  It could be that the list of moves might be being modified by a concurrent thread.

**Comment by Sleet01** [comment] 2024-04-27 18:27
@HoneySkull If you have time, can you check out aace7aa0ae2fa27ac2b7b34ff3cd1730dd2a7358 and see if the same issue occurs?

**Comment by HoneySkull** [comment] 2024-04-27 20:19
@Sleet01 - yes my current dev state includes this pull request:

![image](https://github.com/MegaMek/megamek/assets/83041327/e3acc5e2-513d-4e24-b1f0-4d1c1c972603)

Got this NPE even with this change merged in:

**Comment by HoneySkull** [comment] 2024-04-27 21:01
![image](https://github.com/MegaMek/megamek/assets/83041327/41222018-778e-4c05-b556-9e0a03a71f0d)

It's an interesting note that COORD_SET_LOCK is null here.  This is on Object that gets initialized when the `MovePath` object is instantiated - it's also an object used to synchronize the update of coordsSet which is a SET of Coord object that contain all the hexes of the path.

The reason this is interesting, is because I put a try/catch around the original spot that was thrown and in the catch section, I put some code that called `MovePath::getCoordSet()` and that threw a null pointer exception when trying to sync on that object.

![image](https://github.com/MegaMek/megamek/assets/83041327/84133f3b-5ed9-49de-b1a6-5042c5a93298)

**Comment by HoneySkull** [comment] 2024-04-27 21:04
The other interesting thing to note here is that the path that threw this exception has the same set of move sequences.  Going forward turning around and going forward at the very edge of the map.

**Comment by Thom293** [comment] 2024-04-27 21:05
what PR is this code from?

**Comment by HoneySkull** [comment] 2024-04-27 21:51
![image](https://github.com/MegaMek/megamek/assets/83041327/d8768825-63c8-473e-a137-abf2ba976733)

The root cause of the NPE seems to be Princess generating a move path that has steps positions that take it off the board.
This Thor is trying to go Forward, Turn Left, Turn Left, Turn Left, Forward, Turn Left, Turn Left.

**Comment by HoneySkull** [comment] 2024-04-27 21:53
> what PR is this code from?

https://github.com/HoneySkull/megamek/commit/2acf25c21d4715cc28fc9921a6644584dd2f19be

**Comment by Sleet01** [comment] 2024-04-27 22:11
It's possible my fix for the packet-handling `case` fall through broke this, but I highly doubt it - my guess would be whichever merge caused _that_ issue also contributed to this one.

**Comment by HoneySkull** [comment] 2024-04-28 18:13
From my testing - the breaking commit is here:  02ace957

![image](https://github.com/MegaMek/megamek/assets/83041327/d7e93e7b-1844-4c3e-b37e-eef599c912ab)

The method I found best to test this was to create a game bot vs. bot with each bot being default settings with the parameters listed below:

Bot 1 -> deploy North
Bot 2 -> deploy South

Load bot 1 with this MUL file: Young Wolves.mul
Load bot 2 with this MUL file: Twelfth Falcon Regulars.mul

Load the game parameters from the game options menu:
npe_game_options.xml

[NPE_MUL_OPTIONS.zip](https://github.com/MegaMek/megamek/files/15143125/NPE_MUL_OPTIONS.zip)

On a good commit, the bots will duke it out and the game will finish in around 22 rounds.
On a bad commit, a NPE will occur.

**Closed** 2024-04-28 20:50 UTC
Labels: Bug, Nightly
