### ISSUE TITLE
Vibrabomb early detonation ends movement.

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#527] opened 2017-04-02 23:43 UTC
I was able to duplicate an error another player was having in version 4.30. A mech detonating a vibrabomb early by being to heavy ends that mechs movement, without giving it a chance to plot a new move with leftover MPs. Save attached.

[VibraBombError.sav.gz](https://github.com/MegaMek/megamek/files/888753/VibraBombError.sav.gz)

**Comment by arlith** [comment] 2017-04-27 20:10
Closing as duplicate of #529.

**Closed by arlith** 2017-04-27 20:10 UTC
