### ISSUE TITLE
Bot-controlled droppers in space battle won't move 0.43.2

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#1213] opened 2018-12-26 03:48 UTC
I gave Princess two dropships to fight against my three fighter squadrons, each one consisting of four _Lucifer IIs_ with external stores.  The first turn began and it was Princess' turn to move...  Until she didn't.  Log file is attached.

[megameklog.txt](https://github.com/MegaMek/megamek/files/2709382/megameklog.txt)

**Comment by NickAragua** [comment] 2018-12-26 06:07
Unfortunately, I don't think I'll be able to do anything about this without a save, as I'm unable to reproduce the issue with just the information provided.

**Comment by NickAragua** [comment] 2018-12-28 01:41
The "newtonian movement is disabled" piece proved key to finding the cause of this behavior. Should be fixed for next release.

**Closed by NickAragua** 2018-12-28 01:41 UTC
