### ISSUE TITLE
Rear-mounted small laser not loading on Deva C-DVA-OU Exanimus 0.47.15

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#2546] opened 2021-01-01 15:48 UTC
Looking through some experimental unit files, I noticed that the rear-mounted IS ER Small Laser on the Deva C-DVA-OU Exanimus is not loading.

**Comment by kguuh** [comment] 2021-01-01 15:51
Good

**Comment by sixlettervariables** [comment] 2021-01-01 16:33
Duplicate of https://github.com/MegaMek/megamek/issues/2544

**Closed by sixlettervariables** 2021-01-01 16:33 UTC
Labels: Bug, Duplicate
