### ISSUE TITLE
Megamek no weapons and systems

### ISSUE THREAD

**Issue by VladBesarab** [MegaMek/megamek#1555] opened 2019-11-27 18:38 UTC
MekHQ 0.46.0 Windows 7 Java version 1.8.0_221
First time using MechHQ, I was just testing options, loadouts, mechs, etc. etc. I'm not sure if i broke something but my mechs have no weapons or any systems in megamek. They are listed in mekhq but in megamek there's nothing.
I haven't made any attempts to reproduce it but i tried a few mechs in this save and they are all broken for me, if i add any of them to ai player then they work fine.
Player name(i know it's mistyped):Thousends Sons
Port(not sure if it's important):2346
Hope the screens and files will help.

![MechLabAssignCriticalTab](https://user-images.githubusercontent.com/58269194/69750545-4cfca080-114d-11ea-8a97-2f696cb7e8d4.png)
![MechLabEquipementTab](https://user-images.githubusercontent.com/58269194/69750556-54bc4500-114d-11ea-98ba-ceb5095829d7.png)
![MechLabStructureTab](https://user-images.githubusercontent.com/58269194/69750560-571e9f00-114d-11ea-92c0-8d83c4996430.png)
![Megamek1](https://user-images.githubusercontent.com/58269194/69750565-5980f900-114d-11ea-93a7-bb2a51db5bfd.png)
![Megamek2](https://user-images.githubusercontent.com/58269194/69750571-5b4abc80-114d-11ea-9a9c-8c05b11b6146.png)
![MegamekTurn1systems](https://user-images.githubusercontent.com/58269194/69750577-5d148000-114d-11ea-8c0b-fe23ff058364.png)
![MegamekTurn1weapons](https://user-images.githubusercontent.com/58269194/69750580-5ede4380-114d-11ea-9ef2-efc11dd323b2.png)
![Scenario](https://user-images.githubusercontent.com/58269194/69750584-61d93400-114d-11ea-93f2-7bce7983f053.png)
[Megamek.sav.gz](https://github.com/MegaMek/megamek/files/3898183/Megamek.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/3898186/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/3898187/mekhqlog.txt)
![Hangar screenshot](https://user-images.githubusercontent.com/58269194/69749091-09ecfe00-114a-11ea-8659-a9ad545f38ce.png)

**Comment by HammerGS** [comment] 2019-11-27 18:48
Error from log

```
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 35
	at megamek.client.ui.swing.widget.PilotMapSet.setEntity(PilotMapSet.java:261)
	at megamek.client.ui.swing.widget.PilotMapSet.setEntity(PilotMapSet.java:168)
	at megamek.client.ui.swing.unitDisplay.PilotPanel.displayMech(PilotPanel.java:102)
	at megamek.client.ui.swing.unitDisplay.UnitDisplay.displayEntity(UnitDisplay.java:312)
	at megamek.client.ui.swing.DeploymentDisplay.selectEntity(DeploymentDisplay.java:251)
	at megamek.client.ui.swing.DeploymentDisplay.unitSelected(DeploymentDisplay.java:961)
	at megamek.client.ui.swing.boardview.BoardView1.processBoardViewEvent(BoardView1.java:1158)
	at megamek.client.ui.swing.UnitOverview.isHit(UnitOverview.java:227)
	at megamek.client.ui.swing.boardview.BoardView1.mousePressed(BoardView1.java:4759)
```

**Comment by VladBesarab** [comment] 2019-11-27 18:53
@HammerGS Is it something i can fix or some known/new bug?

**Comment by HammerGS** [comment] 2019-11-27 18:58
I'm just posting the error from the log, Nothing you can fix.

**Comment by binaryspica** [comment] 2019-11-28 12:20
I doubt that it will helps, but did you try to make the mech on MegaMekLab that has the exactly same loadouts and try it on MegaMek? If it works, then at least it would be clear that it would be more like MekHQ bug, I guess.

**Comment by VladBesarab** [comment] 2019-11-28 14:57
@binaryspica just done some tests, if i create the same mech and put it in a different scenario then it does work. I've tried loding the save and replacing my mech with exactly the same one and if i do so then it works fine.
I don't know, some issue with mekhq or in communication between it and megamek.

**Comment by VladBesarab** [comment] 2019-11-28 15:04
Just loaded the campain and gm added a completely diferent mech, didn't change a thing and just deployed it in the same scenario. Same issue, no weapons or systems in megamek.

**Comment by binaryspica** [comment] 2019-11-28 15:47
Then it seems that MekHQ part seems have the real problem, at least.

**Comment by neoancient** [comment] 2019-11-28 22:02
Duplicate of #1549

**Closed by neoancient** 2019-11-28 22:02 UTC
Labels: Duplicate
