### ISSUE TITLE
Dropship Cannot Go Down to Altitude 1

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#53] opened 2016-03-03 09:49 UTC
MegaMek version 0.41.15

"Go Down" button disabled when dropship at altitude 2. Savegame attached. Load savegame, join as SirMegaV for testing.

[DropshipCannotGoDown.sav.gz](https://github.com/MegaMek/megamek/files/156476/DropshipCannotGoDown.sav.gz)

**Comment by arlith** [comment] 2016-03-21 18:57
The reason you cannot go to alt 1 is because the DS has a sensor critical hit.  TW pg 81 says:

> Units with damaged sensors cannot fly at Altitude 1 (NOE).

That's the short of it.  The implications of that are interesting... Basically, it implicitly means that airborne units with sensor criticals can't land.

**Comment by arlith** [comment] 2016-03-21 18:57
I'm going to close this, as technically it's not a bug.  There should perhaps be a way for the UI to inform users about this, but right now that doesn't really exist.

**Closed by arlith** 2016-03-21 18:57 UTC
Labels: question

**Comment by HammerGS** [comment] 2016-03-21 19:04
I'd suggest also asking for a rules clarification from CGL on the official forums.

**Comment by Akjosch** [comment] 2016-03-21 19:54
> That's the short of it. The implications of that are interesting... Basically, it implicitly means that airborne units with sensor criticals can't land.

Well ... lithobraking is always an option. :D

**Comment by pheonixstorm** [comment] 2016-03-22 00:38
that quote from pg 81 refers to the low altitude map not the ground map. Is that save from a low altitude game or ground map? While it does say "Fly" I would suspect the next sentence gives you the answer. Since you can't fly you either land or crash once you go to altitude 1.

**Comment by SirMegaV** [comment] 2016-03-22 02:07
Arith, how about dropping the message at the command box like how it's
informing the Princess is retreating or new window pop-up?

Phoenix, it's ground map.

**Comment by arlith** [comment] 2016-03-22 02:21
It is ground map, but it doesn't matter.  Ground map or low altitude: altitude 1 is still altitude 1.  MM is basically written according to the rule: If you're at altitude 2 and you have a sensor critical, you cannot go to altitude 1.  The rules for landing later says that, if you begin the turn at altitude 1, you may attempt to land.

In my interpretation, I'm assuming that these rules represent a simulation for combat only.  This doesn't imply that a DS could never land with damaged sensor, but just that it cannot land *in a combat situation* with damaged sensor.  **shrug*

I also don't believe you are allowed to intentionally crash.  Crashing generally happens unintentionally...

**Comment by SirMegaV** [comment] 2016-03-22 02:33
I'm not familiar with the rules, but in that game, I did crash
intentionally by not moving and failing the roll. Then I unload my guys
after crash landed.

On Tue, Mar 22, 2016 at 10:21 AM, Nicholas Walczak <notifications@github.com

**Comment by arlith** [comment] 2016-03-22 02:36
Yea, I guess that's an intentional "unintentional."  What I meant to say is that... You can't explicitly make a "crash" movement.  But you can force PSRs that will likely lead to crashes, like trying to hover.
