### ISSUE TITLE
Flare Aritllery Rounds not Illuminating Targets for Visual Detection on Moonless Night

### ISSUE THREAD

**Issue by VictorMorson** [MegaMek/megamek#80] opened 2016-03-15 04:50 UTC
Currently the flare artillery rounds are reducing the to-hit modifier of a target when they have lit an area (which is correct), but fail to illuminate the target for units that have LOS into the illuminated area, like other light sources do (such as fire).

Steps to repro:
1) Set Moonless Night
2) Load up a Vali with Flare Rounds a 0 gunner
3) Put a unit in the dark but in direct LOS of each other (at least 6 hexes away)
4) Fire a flare to illuminate the units
5) Notice that neither unit can see the other, despite being in the lit area

**Comment by arlith** [comment] 2016-03-21 18:04
A saved game would have been useful for this.  Thankfully, the saved game from #81 was suitable.

Turns out, `Compute.inVisualRange` was using `Game.getIlluminatedPositions()` to determine if an `Entity` is illuminated by its position.  This is not correct, and `Game.isPositionIlluminated()` needs to be used instead.

The issue is fixed in 45d428e.  I added a comment to `Game.getIlluminatedPositions()` to indicate that it should not be used for purposes of determining if a `Coords` is illuminated and to instead use `Game.isPositionIlluminated()`.  The different between the two is that, `getIlluminatedPositions()` returns the `HashSet<Coords>` that keeps track of illuminated `Coords` from search lights, while `isPositionIlluminated()` checks that hash set *and* iterates through collections of flares and fires.

**Closed** 2016-03-21 18:04 UTC
Labels: bug
