### ISSUE TITLE
0.45.2: Can't search by troopspace

### ISSUE THREAD

**Issue by mhjacks** [MegaMek/megamek#1235] opened 2019-01-27 21:31 UTC
### Environment
MekHQ 0.45.2 megamek
Linux
Java 8 (Fedora System Java)

### Description
It is not obviously possible to search in the "Add Combat Unit Dialog" by the troopspace attribute, which can be awfully important when selecting the right support vehicle(s), especially VTOLs

**Comment by HammerGS** [comment] 2023-01-23 15:59
Duplicate of https://github.com/MegaMek/megamek/issues/1953

But the recent inclusion of Alpha Strike stats means you can search units via AS criteria.

**Closed by HammerGS** 2023-01-23 15:59 UTC
Labels: Enhancement, GUI, Advanced Search, Duplicate
