### ISSUE TITLE
[0.43.3] Missing unit icons corrupting user interface

### ISSUE THREAD

**Issue by Da-Nuker** [MegaMek/megamek#577] opened 2017-07-27 00:56 UTC
When adding a unit in MegaMek lobby, some units are missing their unit icons or they display the icon of the previously selected unit. Adding such a unit will cause the unit list in the lobby to be garbled and/or the UI buttons in "Add a Combat Unit" to stop functioning.

The problem does not occur in 0.43.2 or previous versions. Some of the units that show this error when selected are:

All 10 ton Armored Personnel Carrier (Wheeled and variants)
All 10 ton Armored Personnel Carrier (Tracked)
10 ton Armored Personal Carrier (Hover Primitive)

Achileus Light Battle Armor (All variants)
Gray Death Standard Battle Armor (All variants)

**Comment by HammerGS** [comment] 2017-07-27 00:59
This is a duplicate of https://github.com/MegaMek/mekhq/issues/414

There is a patch file their but I haven't had any feedback to see if it works.

**Comment by Da-Nuker** [comment] 2017-07-27 01:32
I have tested the replacements images.zip on a fresh copy of Megamek 0.43.3 and the problem still exists.

Verified that vehicles_atlas.png and battle armor_atlas.png were updated with an increase in file size.

**Comment by HammerGS** [comment] 2017-07-27 01:33
Did you place the Mechset file?

**Comment by Da-Nuker** [comment] 2017-07-27 02:09
Yes, confirmed mechset.txt  was replaced but that file is identical to the one included in 0.43.3 release.

**Comment by HammerGS** [comment] 2017-07-27 02:13
Try this one.
[mechset.txt](https://github.com/MegaMek/megamek/files/1178555/mechset.txt)

**Comment by Da-Nuker** [comment] 2017-07-27 02:23
New Mechset.txt tested and it also does not work.

However, if I manually download achileus.png from github and place it into the units\battle armor folder, that works for that unit. 

Also tested with a vehicle Armored Personnel Carrier (Wheeled LRM).png and again it works for that unit and not the other variants with their own png files.

**Comment by HammerGS** [comment] 2017-07-27 02:36
OK, I know I've committed a fix for the next release.  You might need to download the missing images from here and place them in the folders till that release.

**Comment by Da-Nuker** [comment] 2017-07-27 02:43
Got it! Will use that workaround for now for the affected images.

Thank you for all the great work! 👍

**Comment by HammerGS** [comment] 2017-09-02 20:30
Closing as this appears fixed in the Repo

**Closed by HammerGS** 2017-09-02 20:30 UTC
Labels: bug, Data
