### ISSUE TITLE
49.3 : Clicking on another weapon causes the hit calculation to dissapear

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#3187] opened 2021-10-07 06:25 UTC
![image](https://user-images.githubusercontent.com/1191378/136330426-0dd2e1e7-50fd-4517-8457-5a3fd445a935.png)

Picture shows it all, clicking on another weapon causes the hit calculation to dissapear. Pretty sure this did not happen in the last version i played (cant remember which one it was unfortunately).

It shouldnt dissapear, it should re-calculate the to hit and other numbers.

Note that even though it shows no target is selected, the game will still allow you to fire the weapon, so this is probably just a visual glitch.

[megameklog.txt](https://github.com/MegaMek/megamek/files/7299310/megameklog.txt)

Can be replicated in the firing phase if you start a random game with a bot.

**Comment by NickAragua** [comment] 2021-10-10 22:12
This is a duplicate of #2684

**Closed by NickAragua** 2021-10-10 22:12 UTC
Labels: Bug, GUI
