### ISSUE TITLE
0.49.11: Missing Resource File Line

### ISSUE THREAD

**Issue by buzzzz2138** [MegaMek/megamek#4162] opened 2023-02-07 05:54 UTC
### Environment
MekHQ Version and Stand Alone
Windows 10
Java 11

### Description
When clicking on the add bot, nothing happens and the programs locks up.  
See Log File line 562.

### Files
[megamek.log](https://github.com/MegaMek/megamek/files/10671929/megamek.log)
[Save Campaign.zip](https://github.com/MegaMek/megamek/files/10671938/Save.Campaign.zip)

**Comment by pheonixstorm** [comment] 2023-02-18 05:15
I don't think that is the cause of the hangup as there is another portion of the log farther down that lists "Failed loading force template from file CLAN.GC.xml"

But even that likely isn't the cause as the log continues for a few more seconds.

After closing out of MegaMek did you try starting the scenario again with the same result?

**Comment by buzzzz2138** [comment] 2023-02-18 06:04
Yes.  Restarted MekHQ and Megamek. 
I went ahead and re-downloaded MekHQ.  Unzipped with 7-Zip.  Copied over the customs and campaign file and it worked.  I have the the broken version if more logs are needed. 

Not sure what happened.  I didn't delete any files and have successfully been using it since 49.11 was released.

**Comment by Windchild292** [comment] 2023-02-18 06:52
I've resolved this in latest, it was a layered internal resource call issue.

**Closed by Windchild292** 2023-02-18 06:52 UTC
