### ISSUE TITLE
Left Clicking a Unit no longer targets the unit by default.

### ISSUE THREAD

**Issue by sldfgunslinger2766** [MegaMek/megamek#2819] opened 2021-05-02 17:26 UTC
### Environment
v.0.49.0 Dev
Java vendor AdoptOpenJDK
Java version 11.0.10
Platform Windows 10 10.0 (amd64)
Total memory available to MegaMek: 1,048,576 kB

### Description
In past MM versions, left clicking a unit during the targeting phase would target the unit by default, enabling the 'Fire' tab. In this latest Dev version, a player must now right click the unit which then deployes the target/select drop down.

### Files

[megameklog.txt](https://github.com/MegaMek/megamek/files/6411924/megameklog.txt)

**Comment by sldfgunslinger2766** [comment] 2021-05-02 17:55
This behavior also seems to reset torso twisting, but I need to test this further.

**Comment by Tecmes** [comment] 2021-05-02 18:21
Indeed left-click twists the torso, and right-click targets. But it doesn't seem intentional as right-clicking ALSO bring the contextual menu.

Click-twisting would be great, though. Why not shift-clicking? Just sayin'

**Comment by SJuliez** [comment] 2021-05-02 20:29
I can't reproduce this. Shift-clicking twists the torso and left-clicking on some unit targets it. I know of no changes in that area (which of course doesn't mean there can't be some bug).

**Comment by sldfgunslinger2766** [comment] 2021-05-02 23:44
> I can't reproduce this. Shift-clicking twists the torso and left-clicking on some unit targets it. I know of no changes in that area (which of course doesn't mean there can't be some bug).

Right on, maybe I'm just missing something with the torso twist. I've always used the tab at the bottom to choose a twist facing That said, the default left click to target a unit is the main issue.

**Comment by HammerGS** [comment] 2021-05-02 23:47
Out of curiosity, did anyone having the issue copy their mmconfig folder over to the new version?

**Comment by sldfgunslinger2766** [comment] 2021-05-03 00:04
I do tend to copy over a couple of files in mmconf from version to version. But, the log I posted above is from a fresh download of the 49 dev from the website.

**Comment by Tecmes** [comment] 2021-05-03 00:40
Fresh install for me, but I did load a MM prefs from a version saved from 0.48.

**Comment by HoneySkull** [comment] 2021-05-03 14:58
Could Pull Request #2809 have impacted this?  I haven't been able to connect it, but it's plausible.

**Comment by HoneySkull** [comment] 2021-05-03 18:39
I've confirmed this is caused by #2809.  You can see in version 0.48 stable when you left click a target (or other hex) and you hold down the mouse button, a light blue hex boarder appears, and then when you let go of the left mouse button (button up) the unit/hex becomes targeted with a dark blue hex.  

After #2809 was merged, when you left mouse button click, it's like it's only registering the left mouse down but NOT the left mouse up event.  This makes sense since I replaced the deprecated BUTTON1_MASK with BUTTON1_DOWN_MASK as per the JDK11 Swing suggestion.  I'm guessing there is a BUTTON1_UP_MASK that now needs to be included in detecting the event.

**Comment by NickAragua** [comment] 2021-05-04 01:11
Let's let that be a lesson to us all to be wary of willy-nilly replacing deprecated code without testing what it affects.

**Comment by HoneySkull** [comment] 2021-05-04 12:42
Guilty as charged!  Should I roll back the KeyEvent upgrade (#2809) from master and continue to work on the testing/fixing in private or leave it in master and continue to test/fix.  I see @NickAragua has offered a fix - Thank you!

**Comment by Windchild292** [comment] 2021-05-04 12:52
Leave it, Nick's got a fix open for the issue and the overall swapover is an improvement

**Closed** 2021-05-04 14:18 UTC
