### ISSUE TITLE
RFE: Add Unit Role to Advanced Search Options

### ISSUE THREAD

**Issue by stonewall072** [MegaMek/megamek#3877] opened 2022-08-31 12:37 UTC
Pretty much what's in the title, an additional option on the Advanced Search screen that would allow us to filter the unit list by unit role.  Particularly helpful if the player is trying to assemble Campaign Ops appropriate formations (i.e. X lance type needs to have three skirmishers and a brawler, etc.).

**Comment by HammerGS** [comment] 2023-01-23 15:11
Duplicate of https://github.com/MegaMek/megamek/issues/1953

**Closed by HammerGS** 2023-01-23 15:11 UTC
Labels: Enhancement, GUI, Advanced Search, Duplicate
