### ISSUE TITLE
Buildings and Basements in Wrong Apparent Hex

### ISSUE THREAD

**Issue by BairdEC** [MegaMek/megamek#1917] opened 2020-05-05 02:52 UTC
### Environment
MegaMek version 0.47.6, started from MHQ
Win10
Java Version 1.8.0_251

### Description
I had a mek move through clear hexes, and the mek fell into the basement of the building north of him.  The building says "Basement: unknown" on the tool tip.  He also fell into a basement in the clear hex 0624 in the first round.  I had guys stop next to buildings or disallowed from moving through or over buildings.

![Basement](https://user-images.githubusercontent.com/38081112/81030752-c99f5380-8e3e-11ea-8904-49864b421768.PNG)

Movement Phase
-------------------
Building #1905773310 collapses due to heavy load.
    Enforcer ENF-4R (War Wolves) is hit by falling debris for 2 damage.
        Enforcer ENF-4R (War Wolves) takes 2 damage to RL.
            18 Armor remaining.

Enforcer ENF-4R (War Wolves) falls 2 level(s) into hex 1123
    Enforcer ENF-4R (War Wolves) falls on its rear, suffering 18 damage.
        Enforcer ENF-4R (War Wolves) takes 5 damage to RA.
            4 Armor remaining.
        Enforcer ENF-4R (War Wolves) takes 5 damage to LA.
            9 Armor remaining.
        Enforcer ENF-4R (War Wolves) takes 5 damage to CTR.
            Armor destroyed.
             15 Internal Structure remaining.
            Critical hit on CT. Roll is 8; 1 location.
            CRITICAL HIT on Engine.
        Enforcer ENF-4R (War Wolves) takes 3 damage to LL.
            12 Armor remaining.

Pilot of Enforcer ENF-4R (War Wolves) "Lieutenant SG Amberlan Fraisse" must roll 4 to avoid damage; rolls 5 : succeeds.

### Files
[War Wolves30411227.zip](https://github.com/MegaMek/megameklab/files/4578698/War.Wolves30411227.zip)
[customs.zip](https://github.com/MegaMek/megameklab/files/4578700/customs.zip)

[Basement.sav.gz](https://github.com/MegaMek/megameklab/files/4578699/Basement.sav.gz)

**Comment by neoancient** [comment] 2020-05-06 15:09
Duplicate of #1645

**Closed by neoancient** 2020-05-06 15:09 UTC
Labels: Duplicate
