### ISSUE TITLE
Zweihander+Club freezes the program

### ISSUE THREAD

**Issue by Jboreas** [MegaMek/megamek#3363] opened 2022-01-09 13:23 UTC
### **Environment:** 
->Megamek version: 49.6 (also observed in 48.0)
->Java version: 11

### **Description**
Upon using the Zweihander abilty with a Club, the game freezes. Bug observed both in 0.48.0 and 0.49.6 Steps to reproduce the bug from scratch if needed:
**1. Jump into woods+Pick a Club**
**2. Jump next to enemy mech, use Club, click Yes on dialog box for Dice to hit and click Yes on dialog box for using both hands (Zweihander SPA)**
**3. Program "seems" to resolve interaction as if carrying Physical combat phase, but still requires "declare physical attacks"**
**4. Game freezes**
It appears as if the program resolved the damage, see attached screenshot of Grasshopper5H using Zweihander+Club on Panther9R: note the severed arm on the Panther Hex, not present before the attack, but 100% Armour and Structure health bar on the mech. But upon confirming the attack, the severed arm appeared and Megamek required "declare physical attacks"
![bug](https://user-images.githubusercontent.com/97389105/148682850-a236c801-0f46-404b-af6f-cdf2f66ff0fd.PNG)

**5. Upon quicksaving with the program frozen and then loading the quicksave, it "seems" to have resolved the attack, but Megamek is still frozen**
![bug2](https://user-images.githubusercontent.com/97389105/148683554-843b622b-6ac3-4881-893d-6865402e1f0c.PNG)

**6. Already tried and discarded:**
-No issue with Zweihander+Hatchet (tested with Hatchetman)
-No issue with Zweihander+bare hands (tested with Grasshopper)
-No issue with Club use without using Zweihander
-No issue with "Club and Hatchet use punch table" rule enabled
-Memory allocated to Megamek is 4 GB out of 16 GB installed, no issue on other actions on either 0.48.0 or 0.49.6.

**7. Other possible interactions:** 
-Tactical operations optional rules enabled (all save Double blind and sensors), "Club and Hatchet use punch table" already discarded due to bug happening with and without that rule enabled
-SPA Melee specialist (-1 to hit): specifically NOT Melee Master (+1 physical attack)
-SPA Jumping Jack (+1 due to jumping)

### **Files**
-Savegame just before declaring Club attack+Zweihander with Grasshopper armed with a Club (before step 2.): [bugreproduction.sav.gz](https://github.com/MegaMek/megamek/files/7835084/bugreproduction.sav.gz)
Username: Iron Conquerors
-Gamelog: [gamelog.txt](https://github.com/MegaMek/megamek/files/7835083/gamelog.txt)

**Comment by Windchild292** [comment] 2022-01-22 22:30
This is caused by a rule edge case between Zweihander and using an improvised club. I've got a rules query open (https://bg.battletech.com/forums/supplementary-rules/co-zweihander-spa-attacker-damage-using-improvised-clubs/), but will close this report with the implementation of bugfix.

**Closed** 2022-02-01 16:10 UTC
Labels: Bug
