### ISSUE TITLE
Terrain Damage for Engine Explosions and Ammo Explosions

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/megamek#70] opened 2016-03-08 21:11 UTC
With TacOps Engine Explosions and TacOps ammo explosions turned on, the terrain isn't damaged when items/units explode. I would think these types of 'attacks' would flatten woods as if they were artillery strikes (double damage).  This is not new to 41.15, I just don't think it was ever implemented/thought about. 

If this gets added in, it would be worth checking to ensure terrain is not damaged when ammo explodes on a location protected by CASE. 

I also think a Vehicle Explodes critical hit on a vehicle with ICE should roll to set woods on fire if the vehicle is occupying a woods hex.

**Comment by arlith** [comment] 2016-03-08 21:15
Are there any rules that cover this?  I think in these cases, we're mostly interested in adhering to the rules.  Sometimes it's kind of vague when terrain damage should or shouldn't be applied.  It would be useful if you could cite pages and perhaps passages in the rules.

**Comment by mkerensky** [comment] 2016-03-09 14:15
Yes, TacOps covers this (I hadn't read it in a while either).  Page 78 has both ammo and engine explosion rules.  

An engine explosion counts as an Area-Effect Weapon and follows all rules that apply to such weapons. It also starts a fire in the hex of the exploding unit. 

Ammo explosions also count as Area Effect attacks.

Per the Terrain Factor rules starting on Page 64 of TacOps, Area Effect attacks always damage a planetary condition in a hex, inflicting double damage against anything but rough or clear terrain.

I don't guess we have the full TF rules implemented yet. I've noticed none of the terrain types but woods seem to be destructible by fire or weapon attacks, particularly rough, road, paved, rail, swamp and planted field hexes.

**Comment by BLOODWOLF333** [comment] 2016-09-02 01:27
Either not reporting it or not doing it.  TO starting fires rule is on (always Im a pyro)

![example](https://cloud.githubusercontent.com/assets/16950832/18189601/127d4c76-7082-11e6-9af9-bcf8f4c035ca.png)

Player name: BLOODWOLF
[#70.sav.gz](https://github.com/MegaMek/megamek/files/451018/70.sav.gz)

**Comment by BLOODWOLF333** [comment] 2016-09-17 15:22
TO pg.78

"The explosion destroys the unit and all other units in the same
hex, and also starts a fire in the hex, regardless of the terrain
(see p. 43). Any units in adjacent hexes take damage equal to
the engine’s rating divided by 10 (rounded to the nearest whole
number; round .5 down). Units 2 hexes away take damage equal
to the engine’s rating divided by 20. Units 3 hexes away take
damage equal to the engine’s rating divided by 40. Divide this
damage into 5-point Damage Value groupings and randomly
determine each location; determine the direction of the attack
from the direction of the hex where the engine exploded.
Area-Effect Weapon: An engine explosion is treated as an
area-e ect weapon, and so all rules that apply to such weapons
also apply to an engine explosion.
Buildings, Levels (Hills) and Mobile Structures): Use the rules
for Buildings, Levels (Hills) and Mobile Structures as they interact
with artillery when determining the outcome of an engine explosion’s
interaction with such terrain features (see p. 184).
Water: Use the rules for Area E ect Weapons against buildings
(see p. 172, TW) when resolving the damage from an exploding
engine if the target is in a water hex. If the target is not in a water
hex and an adjacent hex is a water hex, no damage is applied to
completely submerged targets in that adjacent hex.
Woods: Woods hexes provide no protection against damage
from engine explosions, even if the Woods Cover (see p. 84) rules
are in use."

**Comment by HammerGS** [comment] 2016-09-17 15:24
Looks like the start a fire part is missing.  I've tested it in a couple of games with no luck as well.

**Comment by arlith** [comment] 2016-09-18 19:56
I didn't re-open the ticket, as I tend to think that the problem is outside of this particular ticket.  Really, it's more that the accidental fires rules need to be updated and worked on...

**Comment by kipstafoo** [comment] 2016-11-03 14:14
Yeah, it might be the accidental fire code. I just finished a fight in a heavy city. I had 3 engine explosions and a 1/2 dozen inferno artillery rounds. Nothing caught on fire. The buildings were damaged from the explosions but there was no fires. None of the explosions started a fire in the hex (regardless of the terrain).

**Closed** 2017-03-28 11:55 UTC
Labels: bug
