### ISSUE TITLE
0.49.13 Map Editor - CTRL-K does not hide (or reveal) the keyboard shortcut overlay

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#4593] opened 2023-07-03 15:21 UTC
MM standalone 0.49.13
Windows 10
Java 11

In the map editor, CTRL-K does not hide the keyboard shortcut overlay.
If the keyboard shortcut overlay was hidden in 'game mode', it cannot be displayed by using CTRL-K.

**Comment by Sleet01** [comment] 2023-08-16 05:41
Taking social lock.  Investigating.

**Comment by Sleet01** [comment] 2023-08-22 17:59
@SimonLandmine I was able to repro this in 0.49.13 MM standalone, but not 0.49.14 or later.  I believe the issue is this:

1. The keyboard shortcut overlay is initially created but not displayed.
2. Whether to display the overlay is decided when loading the GUI preferences.
3. Whether to _enable the keyboard overlay display menu entry and keybinding_ is determined by what view the user is in ("board view" or "not board view").
4. When the menu item or key command is received by the listener, the preference also gets updated.

So everything is working as expected in 0.49.13: from the game board view, you can toggle the overlay off and on.  Additionally, the Map Editor is reading the GUI preferences to decide whether or not to display the overlay, which means changing that state in the Game Board view also changes it for the Map Editor view.
It appears that, in this version, the Map Editor view was not considered a "board view" so the menu entry is disable, which also disables the key binding.  This seems to have changed in 0.49.14 and later.

Can you install 0.49.14 MM standalone and verify that the issue is fixed for you?  If not, there may be a more subtle bug at play.

**Comment by SimonLandmine** [comment] 2023-08-22 23:37
@Sleet01 - Wilco, although it might take me a week or so to have time to check it.

**Comment by SimonLandmine** [comment] 2023-08-30 17:43
Well, the good news appears to be that this is indeed resolved in 0.49.14. Sorted.

The odd news is that, at least in 0.49.14 standalone, the Planetary Conditions overlay appears (or at least the first line of it), but cannot be dismissed ...

![image](https://github.com/MegaMek/megamek/assets/26851644/7e4cfc25-35b0-47d2-a578-9b005d6a5de6)

**Comment by Sleet01** [comment] 2023-08-31 04:47
> Well, the good news appears to be that this is indeed resolved in 0.49.14. Sorted.

I'd like to close this bug, then.

> The odd news is that, in 0.49.14 (standalone and bundle), the Planetary Conditions overlay appears (or at least the first line of it), but cannot be dismissed ... (possibly for a very similar reason, as it's a new feature)
> 
> ![image](https://user-images.githubusercontent.com/26851644/264428027-7e4cfc25-35b0-47d2-a578-9b005d6a5de6.png)

This is possibly a similar bug, especially if it's a new feature.
Another possibility is a bug in the "dirty" or "redraw" state handling, but it'll take me a bit to check that.
Do you mind opening a separate issue for this?

**Comment by SimonLandmine** [comment] 2023-08-31 11:05
No problem! I was just amused that, as we smack one bug ... :-D

**Closed** 2023-08-31 18:37 UTC
Labels: Bug, GUI
