### ISSUE TITLE
[0.44.0 : Bug] Not All "Troops" Carrying Tanks Can Be Generated

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#1077] opened 2018-08-03 02:09 UTC
As titled, common APC units such as APC, heavy APC, Heavy Transport B1 cannot be generated by any factions using RAT Generator even when APC option is selected.

**Comment by Windchild292** [comment] 2020-01-29 19:40
This appears to be a duplicate of #612

**Comment by neoancient** [comment] 2020-01-29 22:13
#612 says it's generating tanks that can't carry troops. This says it's not generating some that can.

**Closed** 2024-07-16 23:25 UTC
Labels: Bug
