### ISSUE TITLE
Written Overview Paragraph Issue

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#2031] opened 2020-06-26 21:38 UTC
v.47.7

'Mechs that have Overview/Capabilities/Deployment sections at the bottom of their "Summary" section (such as the Command COM-2D) only print the first paragraph of each section; if the Mechfile of the COM-2D is opened, it's possible to see that more paragraphs were written but aren't appearing in Megamek itself.

**Comment by HammerGS** [comment] 2020-06-27 19:16
[3039-1.zip](https://github.com/MegaMek/megamek/files/4841107/3039-1.zip)
Sample files for testing.

**Comment by sixlettervariables** [comment] 2020-06-28 14:14
Can we get a screen shot? And do you mean Print as in using a printer?

**Comment by HammerGS** [comment] 2020-06-28 14:31
From the Summary
![image](https://user-images.githubusercontent.com/13752452/85950347-6d761e80-b919-11ea-9c41-a4f8e96cab46.png)

From The TRO
![image](https://user-images.githubusercontent.com/13752452/85950352-79fa7700-b919-11ea-980e-6420c8b651e6.png)

Full Text from file. (Bold is missing)
Overview: The Lyran's attempt at a scout mech, the Commando was viewed as a reasonable alternative to the Wasp and Stinger due to it's superior firepower despite the lack of jump jets.

**Coventry Defense rolled the design out for testing in 2483 and found themselves having to adjust the weapons loadout early on due to heat issues.  Once Coventry Defense overcame these problems the Lyrans officially adopted the Commando into service in 2486.  The design drew the attention of the Terran Hegemony and Star League.  Coventry Defense with the support of the Lyran government played an excellent stall game that kept the design out of the grips of the Star League.**

Capabilities: The armor protection of the Commando is considered weak but the firepower that the Commando brings to bear with any of it's variants ensures that it is an opponent to be respected.

**The combination of armor, firepower, and mobility mean the Commando is best used in hit and run tactics or when an opponent is too focused on another target as it will not be able to withstand return fire for long.**

Deployment: The Commando has earned a distinction in Lyran forces as the Lyrans have a special commendation for scout pilots that go above and beyond the call of duty and Commando pilots feature prominantly on this list.

**Since the fall of the Star League and the chaos of the Succession Wars the Commando has since spread into the service of other nations and mercenaries.**

**Most notable of this is the appearance of Commandos in the hands of the Taurian Defense Force.  Verifiable reports of when they gained this design date back to 3025 but it is possible they gained it sooner.**

**Comment by NickAragua** [comment] 2020-06-29 02:57
Looks like what you want to do is, instead of using the enter key for your line breaks, use "<br/><br/>" - that text is rendered as html and the parser doesn't like newlines.

**Comment by HammerGS** [comment] 2020-06-29 03:39
Thanks, we've found a combination of br/ and p tags works well in the Summary tab. Would there be a way to get one format for both tabs?  Test unit attached.
[Dervish DV-6M-t.zip](https://github.com/MegaMek/megamek/files/4843656/Dervish.DV-6M-t.zip)

Summary Tab
![image](https://user-images.githubusercontent.com/13752452/85970313-5ec65080-b987-11ea-9aa5-42cc01c65910.png) 

In the TRO Tab we got the tags showing.
![image](https://user-images.githubusercontent.com/13752452/85970332-730a4d80-b987-11ea-8136-3580beeea494.png)

**Comment by neoancient** [comment] 2020-06-29 14:27
It's not always tendered as html. It needs to support plain text output also.

**Comment by SJuliez** [comment] 2020-09-23 21:21
See also #1757

**Comment by Windchild292** [comment] 2020-10-01 21:18
I believe this is a duplicate of #1757, thoughts?

**Comment by HammerGS** [comment] 2020-10-01 21:23
I've chatted with AlphaSled and we've got a work around. Not ideal but does work. I'd recommend closing these.

**Closed** 2020-10-01 21:24 UTC
Labels: Bug, UI
