### ISSUE TITLE
Target Loss When Selecting Weapon Returned

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#805] opened 2017-12-20 05:53 UTC
This intermittent issue keeps returning from #212 and #376 third time it is not a coincidence.  And seems like when people reload the save or play megamek again the next day the bug has disappeared.  Target a unit, and then select a different weapon and it clears your target data and have to reselect the unit again.

MekHQ0.43.5 Windows Release
Player Name: BLOODWOLF
[VSAero.sav.gz](https://github.com/MegaMek/megamek/files/1574327/VSAero.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/1574336/megameklog.txt)

**Comment by neoancient** [comment] 2017-12-31 15:28
I can't reproduce it.

**Comment by BLOODWOLF333** [comment] 2017-12-31 17:12
Yep me either after starting a new game.  I honestly dont know how anyone could fix it when it is intermittent like this.  But, this is the third time it has been reported and I want to say it's the first game of a new install?  Is there anyway in the code we could put some kind of logging in it to report if it is clearing the targeted entity after selecting a weapon?  I'm not sure what I can do to help with this.

**Comment by neoancient** [comment] 2017-12-31 18:32
If we could figure out where to log it we would probably figure out what's causing it. It's possible that looking at possible code paths will reveal the problem but other than examining the code and having an inspired insight I don't see this being fixed.

**Comment by BLOODWOLF333** [comment] 2018-07-23 03:54
I have saved and reloaded the game and restarted my PC and I cannot get this bug to go away for this current game I am playing.  Every other time reloading the save has fixed it but, not for this one.

[OCvsFS.sav.gz](https://github.com/MegaMek/megamek/files/2217878/OCvsFS.sav.gz)
BLOODWOLF
Federated Suns (princess bot)
[mmconf.zip](https://github.com/MegaMek/megamek/files/2217880/mmconf.zip)
I just have a feeling maybe this is related to one of my settings in the various xml files of mmconfg

**Comment by kuronekochomusuke** [comment] 2023-02-20 21:50
fixed by #4012

**Closed by kuronekochomusuke** 2023-02-20 21:50 UTC
Labels: Bug, Can't Reproduce
