### ISSUE TITLE
0.49.13 Unit Loading Failures on Custom Infantry Units (possibly heat suit and snow suit)

### ISSUE THREAD

**Issue by mwberlindeu** [MegaMek/megamek#4564] opened 2023-06-24 20:46 UTC
### Environment
0.49.13

### Description
I am getting Unit loading failures on some custom units.
![grafik](https://github.com/MegaMek/megamek/assets/28268113/8244764f-3332-4726-bc8c-2538b61b5e48)
In MegaMekLab validation checks on the units pass (they also worked in 0.49.12
Maybe there is an issue with some suits (heat suit and snow suit) as the weapons are also used on other custom infantry units, and they load without problem. 

### Files
[Custom Units.zip](https://github.com/MegaMek/megamek/files/11858107/Custom.Units.zip)

**Comment by neoancient** [comment] 2023-06-27 17:34
Duplicate of #4452

**Closed by neoancient** 2023-06-27 17:34 UTC
Labels: Duplicate
