### ISSUE TITLE
[0.45.3 : Bug] RAT Generator - Tank - Mission Role "APC" - Not Generating Standard APC, Heavy APC & B1

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#1276] opened 2019-03-01 06:23 UTC
### Environment

MegaMek 0.45.3

### Description

Not generating general APC, Heavy APC and Transport B1 using the RAT Generator - Tank - APC. Instead, I'm seeing units like AC/2 Carrier, LRM & SRM Carrier instead.

**Comment by neoancient** [comment] 2019-03-22 01:27
Closing as duplicate of #612

**Closed by neoancient** 2019-03-22 01:27 UTC
Labels: Duplicate
