### ISSUE TITLE
Have To Type Chat Commands Twice

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#802] opened 2017-12-19 04:07 UTC
![image](https://user-images.githubusercontent.com/16950832/34140364-c453c63c-e43f-11e7-9064-6fc2f6fc13c6.png)

Whether it's /seeall or /checkbv seems like you have to tell MM twice to get it to finally perform the action.  Have noticed this is older version but always forget to say something.

**Comment by SJuliez** [comment] 2020-06-05 17:23
I can't reproduce this in various versions. Don't see how to find this with the given info. OK to close?

**Comment by HammerGS** [comment] 2020-06-05 17:25
I’d close it.

**Closed** 2020-06-05 17:48 UTC
Labels: Bug, Can't Reproduce
