### ISSUE TITLE
RFE: On screen weather/environment symbols.

### ISSUE THREAD

**Issue by Mr-ZenoUK** [MegaMek/megamek#5337] opened 2024-04-09 19:03 UTC
When in a battle you often forget what the weather and environmental conditions are, especially if they are lethal to people.
There is space at the top of the screen in MegaMek to have symbols like those attached so that players can see what the weather/environment is.

Thanks.
![166812](https://github.com/MegaMek/megamek/assets/161900868/75100e3f-932a-43a5-936a-500ac1a33912)

**Comment by Thom293** [comment] 2024-04-09 19:06
Ok now this is a quality idea.

**Comment by gsparks3** [comment] 2024-04-09 22:27
Is this not covered by the existing Planetary Conditions overlay? May not be in the version you are using, depending on which one that is, but it's in 49.18.
![image](https://github.com/MegaMek/megamek/assets/59574316/5abe7638-139e-47ac-acad-ea352e0fde1f)

For the MM lobby, I believe there was also warnings added to notify you of units that will be destroyed by weather, and/or unit search filter options to remove such units from the unit selector.

**Comment by HammerGS** [comment] 2024-04-09 23:59
Closing this was added in 0.49.11 and covers the RFE and is duplicate of https://github.com/MegaMek/megamek/issues/426

**Closed by HammerGS** 2024-04-09 23:59 UTC
Labels: Duplicate, Planetary Conditions
