### ISSUE TITLE
Fires in low light battles don't reveal enemy units

### ISSUE THREAD

**Issue by Shenaldrac** [MegaMek/megamek#168] opened 2016-04-24 16:03 UTC
Been playing Against the Bot, and sometimes there's night battles. At one point, a fire got started accidentally, which illuminated the hex the target was in as well as the surrounding ones. This wou,d I'd imagine, reveal the other units in those hexes, however only those within normal darkness LoS were revealed, the mech out of LoS but within the light of the fire still showed up as a sensor contact. Attached is the save file of the battle, there's the fire, it's Full Moon Night so only 5 hexes of LoS.

Also enemies in fire's light still need to be within LoS or sensor range to be fired upon.

The version of megamek is .0.41.15, the version of MechHQ is 0.3.25

[autosave_2016-04-24_10-54-04.sav.gz](https://github.com/MegaMek/megamek/files/233533/autosave_2016-04-24_10-54-04.sav.gz)

**Comment by VictorMorson** [comment] 2016-05-04 07:46
I've seen a lot of odd behavior at night; including if you light up a target, often other units can't shoot the lit target, which feels odd.  I bugged the illumination rounds not working previously and that was corrected, but I thought fire light worked.

I'd love to see it corrected because I dig night battles in concept.

**Comment by arlith** [comment] 2016-05-05 20:18
I could've sworn that I had checked the code for fires when I fixed the other issues.  I thought I had tested fires, but maybe it only appeared that fires should be working and I didn't test them.

**Comment by arlith** [comment] 2016-05-11 00:33
Well, after I fixed the bug, when I went back to merge the fix into master, my merge conflicts informed me that I had already fixed it.  This issue was caused by the same problem that was fixed in #80.  This game was just created in a version prior to that fix.  I did update the comments a bit further in 72fe2ea.

**Closed by arlith** 2016-05-11 00:33 UTC
