### ISSUE TITLE
Init streak compensation

### ISSUE THREAD

**Issue by TigerShark** [MegaMek/megamek#339] opened 2016-09-23 14:00 UTC
The bonus for init streak compensation doesn't carry over into the re-rolls. 

Example: Player A has lost init for 3 turns and has a +2. Player A rolls a 6 (+2) for an 8. Player B rolls a straight 8. They re-roll. Player A rolls a 8, Player B rolls a 10.

In this case, the 8 should get the +2 for a second tie, but does not.

**Comment by dericpage** [comment] 2016-09-26 17:57
Since this is an unofficial rule, there isn't really a cannon answer for how this should work.  If the re-roll is simply viewed as a tie-breaker rather than a full on re-roll, then not carrying the bonus over would seem to be intended.  On the other hand, do other init bonuses (such as the command mech bonus) carry over?

**Comment by pheonixstorm** [comment] 2016-09-27 00:42
I would think it would carry over (command mech bonus or skills) while for init streak I think the same should apply as well.

As for command mech, I guess that is a good question for the BT forums.

**Comment by arlith** [comment] 2016-09-27 16:32
I didn't look at the text for command mech, but from what I remember it's pretty short.  I did look at TW pg 37 though:
>**INITIATIVE PHASE**
>One player from each side rolls 2D6 and adds the results
>together to determine his team’s Initiative. The team with the
>higher result has Initiative throughout the turn. Re-roll all ties.

It's not exactly explicit, but it indicates that ties are re-rolled.  I would imagine that any re-roll would have the same modifiers.  If modifiers shouldn't be applied, I would expect the wording to mention something about a special tie-breaker roll.

I tend to agree with Deric and that modifiers shouldn't apply, but the rules seem to indicate that they should.

**Comment by wildj79** [comment] 2016-09-27 18:23
Are other modifiers to initiative being used on a re-roll?  E.g. +1 for commander, initiative bonuses added in the lobby...

**Comment by arlith** [comment] 2016-09-27 22:05
I looked at the code.  I'm not 100% sure, but it looks like only the streak compensation isn't applied, and this is very much intentional.  I'm inclined to consider this working as intended.

**Comment by Dylan-M** [comment] 2016-10-09 01:52
related to #345 

And I'm going to disagree with @arlith in part. Perhaps it is intentional that it isn't applied, but it shouldn't be reset eiither.

**Comment by scJazz2** [comment] 2016-10-09 02:33
Posting a log of one of the fights in Epic's Campaign.
The modifier for Command Mech remains along with the CO Init Bonus during the tie-breaker roll. If that is the case I can not see any reason why any other bonuses (ISC) should not also continue to apply for a tie-breaker.

Turns 3 and 4 are the turns of interest, showing the CO and Command Mech bonuses in effect.
[ISC Convo.zip](https://github.com/MegaMek/megamek/files/518062/ISC.Convo.zip)

**Comment by SJuliez** [comment] 2018-03-10 22:38
From the code, I gather that: 
- The init compensation bonus (ICB) does not apply to tie breakers; this is commented as intentional in the code;
- The tie breaker roll itself does not reset the ICB;
- Only winning, whether with tie breaker or directly, resets the ICB

Maybe ICB isnt applied to tie breakers because they're generated by recursively calling the init rolling method and it seemed safer or simpler that way.

I'd agree with @Dylan-M: the system seems ok, a team's ICB doesn't go away until the team wins init.

Therefore I suggest closing this issue.

**Comment by Dylan-M** [comment] 2018-03-12 16:14
I looked at the code further, and there were cases where ICB could be reset for a team when it shouldn't be due to TacGen rerolls. I've split that code out, and fixed the issue in PR #931 

Fixed by #931

**Closed** 2018-03-13 01:09 UTC
Labels: Bug
