### ISSUE TITLE
VTOLs getting bogged down in swamps

### ISSUE THREAD

**Issue by stonewall072** [MegaMek/megamek#3537] opened 2022-03-28 12:32 UTC
0.49.7
Java Vendor: Eclipse Adoptium
Java Version: 11.0.14.1
Platform: Windows 10 10.0 (amd64)

Had an instance where a VTOL passing over a swamp hex had to make, and subsequently failed, a bog down roll. VTOL was flying at level 5.

<img width="896" alt="Screenshot 2022-03-26 175507" src="https://user-images.githubusercontent.com/8825923/160398351-ed754ddb-6238-4fb0-88e3-4893b1902ae3.png">

**Comment by SJuliez** [comment] 2022-04-06 15:13
Closing this as it is a duplicate of #3499

**Closed by SJuliez** 2022-04-06 15:13 UTC
