### ISSUE TITLE
NPE when using shift + next target

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#462] opened 2017-01-05 05:58 UTC
Megamek proceeded to hang when i tried using shift + next target with the first bulldog in the list (which is supposed to select valid targets only).

[mekhqlog.txt](https://github.com/MegaMek/megamek/files/686523/mekhqlog.txt)

[autosave_2017-01-05_16-43-39.sav.gz](https://github.com/MegaMek/megamek/files/686524/autosave_2017-01-05_16-43-39.sav.gz)

Edit : Player name for both files is "Comguards".

**Comment by Question2** [comment] 2017-01-05 12:05
Another NPE, this time using the first lancelot in the list and shift+target.

[mekhqlog.txt](https://github.com/MegaMek/megamek/files/687195/mekhqlog.txt)

[autosave_2017-01-05_22-53-42.sav.gz](https://github.com/MegaMek/megamek/files/687196/autosave_2017-01-05_22-53-42.sav.gz)

**Comment by neoancient** [comment] 2017-01-13 04:15
I was unable to reproduce the same NPE with either save file in the current version or the one used in these games (0.41.28). However, my client stopped responding when I tried to switch to the next valid target with the Lancelot in the second game in the older version. This is due to #444, which has been fixed.

**Comment by neoancient** [comment] 2017-03-05 20:52
Closing issue due to inability to reproduce.

**Closed by neoancient** 2017-03-05 20:52 UTC
