### ISSUE TITLE
Three issues in one:  moving the mouse creates black areas;  icons disappear after movement; and the map resists returning to the area of the about to move unit.

### ISSUE THREAD

**Issue by robertmcrowe** [MegaMek/megamek#251] opened 2016-06-14 17:51 UTC
[MM19stuff.zip](https://github.com/MegaMek/megamek/files/314599/MM19stuff.zip)

**Comment by robertmcrowe** [comment] 2016-06-14 17:52
note: while the icon disappears, the text label does not.

**Comment by arlith** [comment] 2016-06-15 13:36
What appears to be happening here is that there's a super image in the tileset that isn't loading properly.  Given the current logging, I can't tell which, but my plan to fix this will be to add some logging code, so in the future we'll be able to tell if something in a tileset can't be loaded.  I may also write a quick utility for testing too (I think such a tool already exists for the mechsets).

I think I will also add a null-guard to the offending code.  Technically, the way things are written, it *is* possible to get a null image for supers, and the code should reflect this.

**Comment by arlith** [comment] 2016-06-16 13:34
I actually experienced this bug myself, and it's not because of a bad image in the tileset.  I haven't been able to figure out how exactly, but for some reason I had the road supers be an array list with a null entry.

**Comment by arlith** [comment] 2016-07-25 18:27
Closing as a duplicate of #284.

**Closed by arlith** 2016-07-25 18:27 UTC
