### ISSUE TITLE
Dead fire LRM's not following correct rules in 0.48 stable Mega Mek.

### ISSUE THREAD

**Issue by PootisPolice** [MegaMek/megamek#3145] opened 2021-09-08 04:39 UTC
Deadfire LRM's are supposed to be in 5 point clusters according to Intersteller Operations page 132, and no longer roll 3d6 and take the lowest two on clusters.  At the moment the individual missile targeting is crazy OP as of 0.48 Mega Mek.

**Comment by HammerGS** [comment] 2021-09-08 14:39
Closing duplicate of https://github.com/MegaMek/megamek/issues/3147

**Closed by HammerGS** 2021-09-08 14:39 UTC
Labels: Invalid
