### ISSUE TITLE
0.49.x (Linux version) Right clicking on lobby unit fails to produce drop-down menu

### ISSUE THREAD

**Issue by servo01** [MegaMek/megamek#3102] opened 2021-08-24 17:01 UTC
0.49.3
Linux Mint 20.2
openJDK 11.0.11

Linux version of MegaMek fails to produce the drop-down menu (as seen in the attached WINDOWS screenshot) when right-clicking a unit in the lobby and will instead only open the Pilot/Equipment/Deployment popup (as seen in the attached LINUX screenshot) 

Lacking access to the drop-down menu makes it  impossible to configure units, adjust deployment, load onto transports etc..

![Linux Screenshot](https://user-images.githubusercontent.com/30708294/130658309-631e7d39-45a5-4adc-a39c-37df42e775ae.png)

![Windows Screenshot](https://user-images.githubusercontent.com/30708294/130658327-4cda5682-0cf2-4bc8-96ce-c15bce3c0e6c.png)

This issue has been present throughout the 0.49 development branch as reported here: 
https://github.com/MegaMek/megamek/issues/3030

I have spoken with one other player who also reported the issue as being present with his Linux install. 

To recreate this issue open the Linux version of MegaMek into the lobby, add a unit, and right-click on it. 

[megameklog.txt](https://github.com/MegaMek/megamek/files/7040792/megameklog.txt)

**Comment by HammerGS** [comment] 2021-08-24 17:11
Please don't open duplicate issues. 
Duplicate of - https://github.com/MegaMek/megamek/issues/3030

**Comment by servo01** [comment] 2021-08-24 17:21
Is not a hardware issue - as far as I can tell. 

Issue remains present with both track-pad use and USB mice, across multiple laptops as well as multiple Linux distributions.

**Comment by mhjacks** [comment] 2021-09-18 17:31
I can confirm this behavior on FFedora 34 as well.  I am confident that this is not a hardware issue as right-click works elsewhere in my UI.  What extra information would be useful to help troubleshoot/fix this?

**Comment by mhjacks** [comment] 2021-09-25 17:08
To follow up, I did some more troubleshooting with the suggestions of @HammerGS on the slack.

1) Try Oracle JDK - this produced exactly the same results as openjdk did.
2) I could right click on the unit in the "battle" phase of megamek and get the expected context menu in 0.49.3.
2) I installed mekhq 0.48.0 and ran the bundled MegaMek, and was able to get the right-click context menu in the lobby by right clicking there.  That would seem to rule out a driver problem.

An additional node - double right-clicking on a unit in the Lobby brings up the Pilot/Equipment/Deployment dialog for it, same as double left-clicking does.

**Comment by servo01** [comment] 2021-09-25 17:38
Can confirm the same results with all three items

1. Same results using Oracle JDK with various versions of Ubuntu and Mint
2. Same as above. Additionally: Right clicking a HEX (rather than a unit) produces the pop-up menu for Create Special Hex Display/Create Edit Note without issue.
3. Right clicking in lobby for 48.0 also works without issue.  Don't know if relevant, but I seem to remember something about the menus being overhauled in the development branch?

**Comment by mhjacks** [comment] 2021-09-28 01:18
FWIW I did a local build on the issue.3102 branch and confirmed it fixes this issue.  Thanks!

**Closed** 2021-09-28 01:27 UTC
Labels: Bug, GUI
