### ISSUE TITLE
Uncaught exception after closing MegaMek 0.49.8

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#3799] opened 2022-07-21 00:56 UTC
I got an uncaught exception pop-up.  Log file and autosave attached

[UncaughtException.zip](https://github.com/MegaMek/megamek/files/9155328/UncaughtException.zip)
.

**Comment by neoancient** [comment] 2022-07-22 19:47
Duplicate of #3658

**Closed by neoancient** 2022-07-22 19:47 UTC
Labels: Duplicate
