### ISSUE TITLE
41.15 : Moonless night visibility causes strange bright hexes in the upper left of the map

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#115] opened 2016-03-31 00:32 UTC
I noticed that moonless night visibility seems to cause the upper left of the map to be bright while the rest of the map will be darkened during the deployment phase. By default MM has "darkened outside of view" enabled, and all hexes at deployment should be darkened (as you have no units on the board, and everything would be outside your view).

Switching isometric view on/off will reset it and fixes the problem, and so will reloading the savegame.

The number of bright hexes seems to differ, but I can't figure out why.

I can consistently replicate this by starting a new game of MM and setting the visibility to moonless night.

![megamek](https://cloud.githubusercontent.com/assets/1191378/14161873/c79353f4-f732-11e5-8b8d-6f9d876b68a6.jpg)

![megamek2](https://cloud.githubusercontent.com/assets/1191378/14162043/249ac338-f734-11e5-8474-9e58fb075f8d.jpg)

[#battletech.sav.gz](https://github.com/MegaMek/megamek/files/196800/battletech.sav.gz)

[megameklog.txt](https://github.com/MegaMek/megamek/files/196802/megameklog.txt)

**Comment by SJuliez** [comment] 2016-03-31 06:39
Is this about FOV darkening or moonless night? I'm not sure from your post.

When loading a game or starting one I often get a few hexes on screen that are sometimes even not painted at all (i.e. they're empty). This vanishes as soon as the board repaints, which is after a zoom, or indeed changing iso mode.

**Comment by Question2** [comment] 2016-03-31 06:44
Im not sure whats causing this exactly, but it only seems to happen on moonless night or other dark settings. Im not sure if FOV darkening is related, im assuming that the hexes darkening is due to FOV darkening (which may not be correct).

Those tiles are painted, but they are bright while other tiles on the board are dark.

**Comment by arlith** [comment] 2016-03-31 13:36
I think that attaching your clientsettings.xml (from mmconf/) along with a saved game would probably be the easiest way to get this figured out.  Once we can reproduce the issue, it should be easier to find the source.

**Comment by Question2** [comment] 2016-03-31 21:46
But i have attached a saved game, isn't it showing up for you?

**Comment by arlith** [comment] 2016-04-01 02:04
You did, and I see it now.  Huh, I didn't look at the ticket on the webpage before, I only looked at it in email and I could've sworn I didn't see the saved game, but I see it now.

**Comment by SJuliez** [comment] 2016-04-01 15:05
@Question2 I just checked; FOV darkening is not used at all during deployment. So what you are probably seeing is that the image that is placed over hexes to simulate nighttime is not loaded completely for the first few hexes and therefore not applied. The system for this has changed since then, if you use 41.16, you will not get this effect anymore (for nighttime, that is - it can still happen for other images, then you get empty hexes).

I just usually zoom in and out once, problem solved. Going iso and back might be even faster. Since this is a one-time-problem easily circumvented, I'd close this issue for now if ok. Making the board refresh on its own should be done at some point but it isn't pressing.

**Closed** 2016-04-10 09:24 UTC
