### ISSUE TITLE
Feedback on Dockable unit display 

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#3231] opened 2021-11-03 15:16 UTC
From Lisbon
So, a couple of thoughts about the dockable unit display (these are the very first impressions after the battle started):

It's a bit big, as in, bigger than it needs to. All the info is the same, but the space is almost double on my monitor compared to the little window I usually have on the corner just outside the main battle window
When using the display as that mentioned little window, the elements in the various tabs don't update very well, specially the armor and the "extras" tab, because in the undocked version they keep the format of the original docked one, so unless we use a large height for the window, a couple of elements get hidden
Minor stuff, but I figured I would share"
and

A bit of extra feedback: the game no longer saves unit display window position, so every time you load a game, the unit display is docked. It also doesn't save size (but it does save position) within the same game session

@mjog

**Comment by HoneySkull** [comment] 2021-11-03 18:55
I noticed when the window is undocked and you re-size the unit display, especially with the Armor tab, the positioning of the content isn't relative to the window as Hammer stated above.  As a result, the window is required to be larger than in has to be in order to see the full content.

Might be kind of nice to have an over/under tab configuration so you could see two tabs at once.  (i.e. The armor tab is always on top, and then have the remaining tabs on the lower half of the docked window.  Having the armor and weapons tabs always visible would be sweet.

**Comment by JonhyBurner** [comment] 2021-11-03 19:14
The possibility to have a double display, of our unit and the target, is also interesting.

I also think that the docked display could be slimmer or the user be able to choose a width, because on a 16:9 monitor it occupies a lot of space that could (should) be otherwise occupied with more map.

**Comment by mjog** [comment] 2021-11-03 23:51
NB: fixes for this stuff going up over in #3233

**Comment by mjog** [comment] 2021-11-03 23:56
@HoneySkull 

> I noticed when the window is undocked and you re-size the unit display, especially with the Armor tab, the positioning of the content isn't relative to the window as Hammer stated above. As a result, the window is required to be larger than in has to be in order to see the full content.

Will see what I can do about that - might be a layout issue? Can you provide screenshot(s) that illustrate the issue though?

> Might be kind of nice to have an over/under tab configuration so you could see two tabs at once. (i.e. The armor tab is always on top, and then have the remaining tabs on the lower half of the docked window. Having the armor and weapons tabs always visible would be sweet

Yeah that sounds like a good approach to explore - but tbh the unit display code is all custom rendering and themed images, it's a bit of a mess, so probably outside the scope of this for the moment.

**Comment by mjog** [comment] 2021-11-04 00:03
> The possibility to have a double display, of our unit and the target, is also interesting.

Yeah I'd like this as well. Probably out of scope here though. Maybe open a new issue as a feature request?

> I also think that the docked display could be slimmer or the user be able to choose a width, because on a 16:9 monitor it occupies a lot of space that could (should) be otherwise occupied with more map.

This is related to my last comment just above about the unit display code being a mess of custom rendering and layout code. I'll look into it, but to get this fixed properly (i.e. have it Just Work™) would probably mean re-writing it all to use standard Swing widgets.

**Comment by mjog** [comment] 2021-11-07 09:56
Just pushed a fix for the attached unit detail pane being a bit larger than it needs to be. This makes it ~15% less wide than it is previously. It can't really be made any smaller since it will either start compressing widgets such that they are not usable (Systems pane) or obscuring widgets (tab bar and Extras pane). If people would like to make it smaller than that regardless, they can always detach it.

Re the space around the Armour and Extras panes, I still can't reproduce the issue. Prodding the unit display to re-check its sizing on detach doesn't seem to do anything, and when resizing the detached pane, the Armour and Extras pane seem to resize as I would expect. So I'd really need to see a screenshot or something to work out what people mean there.

Note that the Extras pane is /very/ long, and for me requires a minimum size of 258x810 px - way larger than any other panes. Also, the Systems pane needs a big chunk of width to be usable. So I wonder if people are just typically using smaller unit detail windows despite the fact it makes those panes unusable, since they don't get used much? If so, again this isn't the right place to fix that, since it would be a lot of changes.

**Comment by JonhyBurner** [comment] 2021-11-07 10:31
That 15% reduction seems just fine, since that would make it as wide as the tabs (I would have to try it to make sure). You are right about people making the display even shorter, but you are also right when saying it would look bad on the docked version.

The armor pane issue is that when the unit display is detached, the armor graphics barely move up when the window is resized, and leave a good empty space above it. That means that the window gets too tall, and the armor graphics are near the bottom of the window, like so:

![Screenshot 2021-11-07 102415](https://user-images.githubusercontent.com/67933202/140641179-c7458f40-be38-4f86-bee7-970522e0786f.png)

The extras pane has a lot of info, so it's big on its own right, but if it could be scrolled down when undocked, it would solve the issue. The system pane could be improved likewise, but making the scrolling inside the systems/components list on the right side. Not sure if it's possible.

**Comment by mjog** [comment] 2021-11-09 11:25
> That 15% reduction seems just fine, since that would make it as wide as the tabs (I would have to try it to make sure). You are right about people making the display even shorter, but you are also right when saying it would look bad on the docked version.

Yeah it's a lot closer to the tab width for me. That will change depending on people's font size, but this change will let the attached version be as narrow as the unit display will let it be.

> The armor pane issue is that when the unit display is detached, the armor graphics barely move up when the window is resized, and leave a good empty space above it. That means that the window gets too tall, and the armor graphics are near the bottom of the window, like so:

Ah I see. Yeah that's also caused by the extremely long Extras tab. You can see the same thing with the Systems tab - it's really long despite it not needing to be. And both are caused by the Extras tab's setting the effective minimum height for all of them. In the case of the Armour tab, it's probably being centred with have of the expected height being off screen.

> The extras pane has a lot of info, so it's big on its own right, but if it could be scrolled down when undocked, it would solve the issue. The system pane could be improved likewise, but making the scrolling inside the systems/components list on the right side. Not sure if it's possible.

That or some other solution is likely possible, but again not likely worth fixing here since it's actually a pre-existing problem with the unit display itself.

**Closed** 2021-11-09 14:21 UTC
