### ISSUE TITLE
[3.29] Height 1 building prevents mech from being punched. 

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#289] opened 2016-07-27 03:26 UTC

**Comment by beerockxs** [comment] 2016-07-27 11:11
That's not a bug. While in a building, a 'Mech is considered to be only one level high.

**Comment by arlith** [comment] 2016-07-27 12:43
Given that and the utter lack of details, I'm going to close this.

**Closed by arlith** 2016-07-27 12:43 UTC

**Comment by VampireSeraphin** [comment] 2016-07-27 14:44
I didn't add any details because it seemed like an ultra simple issue. Mechs are height 2, if one is standing in a height 1 building, it should be able to be punched, clubbed, or kicked in the head by a unit above it. Further, the building acts as full instead of partial cover, which is also silly since its half exposed.

The code for partly exposed mechs must already be in place. It works for partly submerged mechs.

Surely there is errata somewhere that covers these problems.

**Comment by beerockxs** [comment] 2016-07-27 14:45
No. While in buildings, Mechs are height 1. That's the rules.

**Comment by wildj79** [comment] 2016-07-27 15:02
@VampireSeraphin See p. 171 of Total Warfare:

> **Physical Attacks:** Physical attacks cannot be made against
targets in a building hex by units outside the hex, unless the
attacker is located in the same multi-hex building and is adjacent
to the target, on the same level of the building hex (see
Combat Within Buildings, p. 175).

**Comment by arlith** [comment] 2016-07-27 15:26
This is why details are important.  If you can attach a screenshot to describe your situation, reference the rules involved, and attach a saved game, it saves significant time and frustration on the part of the devs.  It may take you 30 seconds to type up your description, and then 15 minutes of developer time sorting through it.  Compute that over 10's or 100's of reports and that's a lot of time trying to figure out someones issue that could actually be spent on *fixing* someone's issue.

**Comment by VampireSeraphin** [comment] 2016-07-27 15:51
Very well, from the beginning then. I do not have a save game, the game is saved on another players server. I'll get a copy, _but I believe MM is working as intended, merely in a way that is silly_. To me, this situation seems like an oversight in the rules. I don't know that I'll be able to get a screenshot, I'll ask him if paranoid autosave was turned on, it should be per the rules we use.

Specifically, my opponent moved his Thunderbolt into a height 1 building. I am aware that battlemechs in buildings cannot be physically attacked, and buildings reduce damage against them. However, I have not been presented with this specific edge case before, a mech in a building only waist high. So, I moved a Battlemaster into punching position to see if I could hit his mechs upper section. It seemed plausible at that time that the building would be treated by MM as only protecting the lower portions of the mech, because it was to short to protect the upper works. Likewise I was hoping it would treat the building as partial cover, with the legs protected the same way a hill would afford, with damage rolls to the legs striking the building. I was disappointed on both counts. MM treated the building as if it covered the entire mech, even though it clearly did not.

If this is the RAW functioning correctly, then there is an oversight in the rules. I am going to get on the BT forums, and see if there is any errata about it. If not, I intend to reach out to CGL for clarification.

**Comment by wildj79** [comment] 2016-07-27 16:09
@VampireSeraphin The rules from Total Warfare are quite clear on this case. See p. 171:

> **ATTACKING UNITS INSIDE BUILDINGS**
> Players may make attacks against units inside a building
hex. Any attacker must have a valid LOS to the building hex,
as well as the level within the building hex occupied by the
target unit. Like woods, building hexes block line of sight,
but the building hex a unit occupies is not considered when
determining LOS. A unit firing at non-infantry units inside a
building hex does not modify the to-hit number to represent
this situation, but the building provides some protection
against damage to the non-infantry units.

> Attacks against infantry in a building hex use different rules;
see Infantry Inside Buildings, p. 172.

> From each attack that hits a unit inside the building, the hex
absorbs an amount of damage equal to its CF at the beginning
of the current phase, divided by 10 (round up). For this
purpose, treat as a separate attack each individual Damage
Value grouping for which the attacker would make a hit location
roll, including all cluster weapons (LRMs, individual LB-X
autocannon flechettes from Cluster Ammo and so on) as well
as individual conventional infantry Damage Value groupings.
The building hex absorbs the same amount of damage from
each attack. Resolve the damage (reducing the CF) only after
all weapons fire is complete.

> All missed shots aimed at a target inside a building hex
do not damage the building hex; in addition, when a cluster
weapon successfully strikes a target inside a building hex
(unless the attacker is adjacent, in which case all missed shots
automatically strike the building hex), any damage that does
not strike the target as indicated by a roll on the Cluster Hits
Table also does not damage the building hex.

Megamek is functioning within the rules in this case.

**Comment by beerockxs** [comment] 2016-07-27 19:36
Here's the explicit question regarding this on the rules questions forum:
http://bg.battletech.com/forums/index.php?topic=1483.msg42098#msg42098

**Comment by VampireSeraphin** [comment] 2016-07-27 21:28
Yeah, I asked around the errata section of the forum, and there are no published revisions or exceptions. Everything is working as intended, so I'm going to let this drop. 

I do want to go on record saying this is a dumb rule though. Extremely illogical.

**Comment by arlith** [comment] 2016-07-27 22:58
I think the idea is that if a lvl 2 mech is in a lvl 1 building, then it's got to be crouching down in some manner; it's *inside* the building, not sticking up like it's wearing some type of building-pants. (Not that this is the only questionable rule...)

**Comment by VampireSeraphin** [comment] 2016-07-28 00:27
I'm seeing it as the mech striding through the building, and kicking it out of the way. For everything except attacks against the mech, LOS to & from, ability to make own attacks, etc... the mech is still considered height 2. That does not suggest a crouch to me.

The part that really bugs me though, is that this game has thousands of rules, including dozens of edge cases. However, something simple & logical like this gets pretty much handwaved. Apparently, the height 1 building protects the mech's chest through some sort of black magic. Perhaps it jumps up an intercepts incoming attacks.

There really ought to be an exception written into the rules so that a height 1 building absorbs attacks like a partial cover hill, and only blocks kicks/attacks from below. I don't understand why there is not, and the link posted above is from 4 years ago, so I don't expect them to suddenly change it now :(

**Comment by pheonixstorm** [comment] 2016-07-28 03:47
I think this would be a good candidate for an unofficial rule. L1 building only blocks shot to the lower legs (possibly as partial cover to make things easier) while leaving the torso etc exposed. Would it be difficult to code arlith or worthwhile?

**Comment by arlith** [comment] 2016-07-28 12:00
I'm not certain about how difficult it would be, but I'm also not very keen on adding it.  Tbh, I think this is super unimportant, and a situation that's unlikely to arise.  I know that there are already a large number of options, but I think it's important to not just add options frivolously.  Each option adds complexity to the codebase.

**Comment by pheonixstorm** [comment] 2016-07-29 03:52
But the codebase already needs an overhaul. 15 years of constant development has left certain areas difficult to understand and as other areas are fixed opens up a host of new bugs from time to time.

**Comment by HammerGS** [comment] 2016-07-29 14:59
@pheonixstorm So are you saying we should add more unofficial rules to a "codebase already needs an overhaul"

Cause as you say.... "opens up a host of new bugs from time to time"

**Comment by pheonixstorm** [comment] 2016-07-30 10:39
Exactly! j/k

It would be a nice optional feature, but if as arlith says each new (optional) feature is dragging things down it may be high time to think about an overhaul after this or the next stable to clean out the clutter left over from 15 years of changes. Not a fun prospect but the only other alternative is to completely rewrite MegaMek from scratch. My thoughts anyway.
