### ISSUE TITLE
[0.50.01-SNAPSHOT] Clan Weapons in Large Craft Weapons Bays lose their ammunition upon reconfiguring

### ISSUE THREAD

**Issue by FunAndEngaging** [MegaMek/megamek#6162] opened 2024-10-31 22:29 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

![image](https://github.com/user-attachments/assets/bcde02ad-1f67-4f8c-bd1c-253793aa030b)

I have tested this on 10+ different units. Weapons bays consisting of Clan weapons - with appropriate ammo assigned to them in the .blk file - irretrievably lose their ammunition in all these bays after being reconfigured in the lobby.

The only workaround is never touching the unit configuration at all. I've tried setting all options regarding unofficial equipment and cross-tech ammo, to no avail. I've also tested it with a custom mixed-tech unit, and again only the CL-tech weapons were affected.

### Steps to Reproduce

1. Add a Large Craft with Standard-Scale CL weapons (e.g. Leviathan III)
2. Open the equipment reconfiguration menu. Observe lack of options for all weapons that do not have an IS/All tech base, like capital weapons do
3. Overwrite the default ammo loadout from the loaded .blk by making any change (e.g. pilot changing skill level)
4.  Observe how the conventional ammunition is permanently lost and the unit is declared illegal due to lack of minimum ammunition
5.  Check the unit preview to see that the ammo bins are now empty

![image](https://github.com/user-attachments/assets/4690e43a-ae26-489f-83db-77b90dc8e1c3)

### Operating System *

Linux

### Java Version *

17.0.11

### MegaMek Suite Version *

Free Text (type manually)

### Custom MegaMek Version

0.50.01-SNAPSHOT

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by SJuliez** [comment] 2024-11-01 15:51
I can't reproduce this. Year 3151, added a Leviathan III, configured mulitple times, everything looked ok. We've recently merged a fix for something that looked like that issue. Are you using the very latest version?

**Comment by FunAndEngaging** [comment] 2024-11-01 18:28
> Are you using the very latest version

I was certain I was, but the build date in the log said otherwise. I don't know how I did it, but I seem to have downloaded the latest nightly yesterday and then proceeded to extract the 0.50 release version instead.

Having corrected that, I can confirm that the ammo is fixed now.

Sorry for the confusion.

**Closed** 2024-11-01 18:29 UTC
Labels: Can't Reproduce, Severity: High
