### ISSUE TITLE
Bug: LAM deployed from MekHQ comes in as invalid design, missing jump jets

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megamek#2667] opened 2021-02-18 19:25 UTC
Using 47.16, starting from MekHQ, when some LAM designs are deployed either as OpFor or as an ally they are missing several jump jets and flagged as an invalid design:

![LAM_error](https://user-images.githubusercontent.com/70451747/108409708-cade1900-71e3-11eb-81fc-a4ae6f0cdabd.png)
[LAM_error.sav.gz](https://github.com/MegaMek/megamek/files/6005297/LAM_error.sav.gz)

When they are added manually in the lobby, everything is fine.

**Comment by SuperStucco** [comment] 2021-03-20 20:28
Still happening in 48.0.

[Hagaar's Hornets30671125.cpnx.gz](https://github.com/MegaMek/megamek/files/6176365/Hagaar.s.Hornets30671125.cpnx.gz)

**Comment by Windchild292** [comment] 2021-03-20 20:29
The issue is still open. Issues are only fixed once they are closed.

**Comment by mjbroekman** [comment] 2022-05-16 16:38
This is a data issue. It seems there are two WSP-105 designs. When I look for it in MegaMekLab, there is a 6/9/6 WSP-105 and a 6/9/2 WSP-105.

**Comment by mjbroekman** [comment] 2022-05-16 16:51
It looks like the files in unsupported.zp (both WSP-105-M and WSP-105) are 6/9/2 "broken" LAMs. The WSP-105M and WSP-105 in mechs.zip are both 6/9/6 "functional" LAMs:
```data/mechfiles$ unzip -l unsupported.zip | grep LAM | grep Wasp
     1672  02-17-2022 20:39   mechs/3025 IS/Wasp LAM WSP-105-M.mtf
     1585  02-17-2022 20:39   mechs/3025 IS/Wasp LAM WSP-105.mtf
data/mechfiles$ unzip -l mechs.zip | grep LAM | grep Wasp
     3715  02-17-2022 20:39   LAMS/Wasp LAM Mk I WSP-100.mtf
     3497  02-17-2022 20:39   LAMS/Wasp LAM Mk I WSP-100A.mtf
     3659  02-17-2022 20:39   LAMS/Wasp LAM Mk I WSP-100b.mtf
     3440  02-17-2022 20:39   LAMS/Wasp LAM WSP-105.mtf
     3408  02-17-2022 20:39   LAMS/Wasp LAM WSP-105M.mtf
     3785  02-17-2022 20:39   LAMS/Wasp LAM WSP-110.mtf```

**Comment by mjbroekman** [comment] 2022-05-16 17:16
Further investigation has found the following about files in `unsupported.zip` :
- 3025 IS files all have too few jumpjets
- Orca (Clan) is over-tonnage (239 tons vs max of 200 tons)
- 3055 IS files are either over-tonnage (55.5 tons vs 55) or too few jumpjets or unsupported equipment (endo/ferro/XL on LAM)

Deleting the `unsupported.zip` file and the `units.cache` in data/mechfiles/ will rebuild the cache without these broken designs.

**Comment by SuperStucco** [comment] 2022-05-16 17:37
Interesting.  MegaMekLab, MekHQ Unit Market and refit dialogs, and the MegaMek lobby would only show me the 'supported' ones with the correct stats and no duplicate entries.  The problem only comes up when units are transferred from a MekHQ scenario to the MegaMek session.  Might be worth checking the entire inventory for potential duplicate chassis/model combinations to avoid similar issues.  Maybe submitting a separate request for better duplicate handling e.g. warning dialog or at least have it added to the log?

I'll give that solution a try (I'm old school, so they'll get renamed with an '.old' suffix rather than deletion) and see if that helps.

**Comment by SuperStucco** [comment] 2022-05-17 18:36
> EDIT: Is there a way to hyperlink a big posted in MHQ from the MM issue tracker? If I put number symbol and bug here, it only references the MM bug of that number.

From the three dots at the upper right of a post, you can select some options for linking. Like this: https://github.com/MegaMek/megamek/issues/2667#issuecomment-1129152414

With the text looking like this in the reply box:
`https://github.com/MegaMek/megamek/issues/2667#issuecomment-1129152414`

**Comment by Thom293** [comment] 2022-05-17 19:08
Thank you!

**Closed** 2022-11-29 21:37 UTC
Labels: Bug
