### ISSUE TITLE
Trailer MP reduction seems not working properly

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megamek#1467] opened 2019-09-02 12:58 UTC
### Environment
Ver 0.47.0
Windows 7

### Description
I post this just because I wonder it is a bug or trailer is not fully implemented in MegaMek. 

Per p. 101, TechManual(and errata), the MP of Tractor-Trailer is 

> ( _Engine Rating of Tractor_ **+** _Lowest Suspension Factor of combined Tractor and Trailer_ ) ÷ (Combined weight of all Tractor and Trailer)
And round down the result.

So, for example, if I have a 75 ton tracked tractor and 375 engine(Cruise MP 5) and a 50 ton tracked trailer, and attach the trailer to the tractor, The end result should be (375+0)/(75+50)= 3.0. But in MegaMek, for now the tractor's MP is reduced to 2, not 3.

Again, I don't know if it is fully implemented or not so it is possible that you guys are already aware of the problem(and it seems that implement tractor-trailer seems complicated), so if you are already aware of this then it is fine.

**Comment by mkerensky** [comment] 2020-04-01 15:40
I'll take this one.  I don't think suspension factor is being accounted for correctly in the calculation.

**Comment by mkerensky** [comment] 2020-04-07 16:43
Fix written. Will be available with the next release.

**Comment by binaryspica** [comment] 2020-04-07 16:48
Thanks! Can I close the thread then?

**Comment by Windchild292** [comment] 2020-04-07 16:48
It will close when the issue is merged :)

**Comment by binaryspica** [comment] 2020-04-07 16:50
Alright. Thanks for the hard work!

**Comment by SJuliez** [comment] 2020-05-31 10:17
Can this be closed because of PR #1844 ?

**Comment by Windchild292** [comment] 2020-05-31 16:20
Fixed in #1844

**Closed by Windchild292** 2020-05-31 16:20 UTC
