### ISSUE TITLE
Uncaught Exception When Attacking With AP Weapon Other Than Generic on Battle Armor 0.49.13

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#4480] opened 2023-06-03 12:15 UTC
MegaMek throws an Uncaught Exception when I try to attack with an anti-personnel weapon mounted in the modular AP weapon mount on Battle Armor other than the default generic weapon.  Steps to reproduce:

1) Choose a Battle Armor squad with a modular AP weapon mount.  Elementals are my go-to.
2) Choose an AP weapon other than the Generic one.  Mausers are also my go-to.
3) Go into a game and try to make an attack with the weapon in the Weapon Attack Phase.  Uncaught Exception window pops up.  This doesn't appear to affect the default Generic AP weapon.  The exception can be bypassed by clicking "Ok" and reselecting the target with the AP weapon still selected.

Log attached.

If it's useful, this bug also occurred in 0.49.12.

[megamek.log](https://github.com/MegaMek/megamek/files/11642591/megamek.log)

**Comment by gsparks3** [comment] 2023-06-03 12:33
Duplicate of #3494 

Note that if the BA suit has no other damaging weapons, the error can no longer be bypassed (at least when I tested it), and will instead cause the game to lock up.

**Comment by kuronekochomusuke** [comment] 2023-06-03 16:11
looks like an issue with the lobby configure also, it does not unselect any previous selected weapons.  so it keeps adding them, if you go back in an try to update after adding one

![image](https://github.com/MegaMek/megamek/assets/116095479/6a5c41c8-c40b-412f-b9e0-771ef0483ed0)


![image](https://github.com/MegaMek/megamek/assets/116095479/917f24f4-9830-48db-9ecb-db04bf656674)

**Closed** 2023-06-07 16:50 UTC
Labels: Bug
