### ISSUE TITLE
Bimodal LAM unit images do not load

### ISSUE THREAD

**Issue by SVNaas** [MegaMek/megamek#1355] opened 2019-05-30 04:56 UTC
### Environment
MegaMek 0.45.4
Windows 10
Java version 1.8.0_192

### Description
Bimodal LAMs do not load their own images if they exist and are defined via exact in localclient_mechset, they instead load the default LAM images. If no image is set then it will load the chassis default should it exist and the default LAM fighter image.

**Comment by SVNaas** [comment] 2019-05-30 05:09
Upon further testing if defined via Chassis and contains a model number in the filename it seems to break select and close and close, once the unit has been selected causing task manager to be the only exit method. If it does not have a model name defined and only the chassis then it will display the correct LAM Fighter image, however, once spawned in the unit is invisible in the lobby. Though it may still be clicked.

**Comment by neoancient** [comment] 2019-05-30 14:32
A model number in which filename? The unit? The image?
Please attach the log file.

**Comment by neoancient** [comment] 2019-06-21 19:42
Closing due to insufficient information to reproduce.

**Closed by neoancient** 2019-06-21 19:42 UTC

**Comment by SVNaas** [comment] 2019-06-22 14:39
Behaviour noticed with this unit, however the issue with the images using the default persists with canon units as well. Log didn't contain anything. Delayed response due to github being sorted into spam.

[unit.zip](https://github.com/MegaMek/megamek/files/3316928/unit.zip)

**Comment by neoancient** [comment] 2019-06-22 15:42
I don't see a problem.
![Screenshot from 2019-06-22 10-38-15](https://user-images.githubusercontent.com/16927464/59965902-f9b95e80-94d9-11e9-9560-0d4e7c4d8ef5.png)

I put the images in `data/images/units/mechs` and added these two lines to localclient_mechset.txt:
>>>
exact "Murasame LAM M11-C" "mechs/Murasame LAM M-11C Mech.png"
exact "Murasame LAM M11-C_fighter" "mechs/Murasame LAM M-11C Fighter.png"

One thing I noticed is that the model name and the image filenames have the hyphen in different places.
