### ISSUE TITLE
MegaMek battle received error "uncaught java.lang.NullPointerException detected."

### ISSUE THREAD

**Issue by TalRaziid** [MegaMek/megamek#5796] opened 2024-07-24 23:43 UTC
### Environment
15:24:49,046 INFO  [megamek.MegaMek] {main}
megamek.MegaMek.initializeLogging(MegaMek.java:118) - Starting MegaMek v0.49.20
	Build Date: 2024-06-28T16:07:06.718979300
	Today: 2024-07-24
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.12
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 2 GB
	MM Code Revision: Unknown
	MML Code Revision: Unknown
	MHQ Code Revision: Unknown
### Description
During battle at end of phase, game experience a null pointer error

### Files
[issue report.zip](https://github.com/user-attachments/files/16368429/issue.report.zip)

**Comment by IllianiCBT** [comment] 2024-07-26 00:03
Transferred to mm, as the issue is occurring in that client.

I believe there has been some discussion about this issue on Discord. Maybe about a disconnect or something. Would someone be able to provide an update so whoever tries to tackle the bug is fully informed? :)

**Comment by HammerGS** [comment] 2024-07-26 00:19
```
17:16:18,427 ERROR [megamek.client.AbstractClient] {AWT-EventQueue-0}
megamek.client.AbstractClient.handlePacket(AbstractClient.java:383) - Failed to parse Packet command PHASE_CHANGE
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 10
	at java.base/java.util.Vector.elementData(Unknown Source)
	at java.base/java.util.Vector.get(Unknown Source)
	at megamek.common.Game.getTurnForPlayer(Game.java:612)
	at megamek.client.Client.isMyTurn(Client.java:205)
	at megamek.client.ui.swing.boardview.TurnDetailsOverlay.gameTurnOrPhaseChange(TurnDetailsOverlay.java:58)
	at megamek.client.ui.swing.boardview.AbstractBoardViewOverlay$1.gamePhaseChange(AbstractBoardViewOverlay.java:245)
	at megamek.common.event.GamePhaseChangeEvent.fireEvent(GamePhaseChangeEvent.java:68)
	at megamek.common.AbstractGame.fireGameEvent(AbstractGame.java:173)
	at megamek.common.Game.processGameEvent(Game.java:739)
	at megamek.common.Game.setPhase(Game.java:735)
	at megamek.common.IGame.receivePhase(IGame.java:110)
	at megamek.client.AbstractClient.changePhase(AbstractClient.java:488)
	at megamek.client.Client.changePhase(Client.java:187)
	at megamek.client.AbstractClient.handleGameIndependentPacket(AbstractClient.java:465)
	at megamek.client.AbstractClient.handlePacket(AbstractClient.java:376)
	at megamek.client.AbstractClient$1.lambda$packetReceived$0(AbstractClient.java:531)
```

**Comment by repligator** [comment] 2024-07-26 01:43
> Transferred to mm, as the issue is occurring in that client.
> 
> I believe there has been some discussion about this issue on Discord. Maybe about a disconnect or something. Would someone be able to provide an update so whoever tries to tackle the bug is fully informed? :)

From Discord

> Tal'Raziid: had this happen twice in this battle and i dont know of anythign related to the first time
> Tal'Raziid: hm. wonder if its related to something dying that turn
> Tal'Raziid: hm nope
> Tal'Raziid: cant even /victory it
> . . . 
> sleet01: It looks like the MegeMek game has actually died or lost its connection to MHQ...
> Tal'Raziid: Would this be caused by an internet  connection dropping out?
> sleet01: That's one possibility, if the game server were remote. The other possibility that comes to mind is that the NPE killed the MM game instance, and it returned a bunch of errors to MHQ right as it was disconnecting.

**Comment by repligator** [comment] 2024-07-26 13:36
Using 49.20, I was able to load and play the game to completion, without hitting an NPE. The picture is from right after loading.
[Battle.zip](https://github.com/user-attachments/files/16392416/Battle.zip)

**Comment by TalRaziid** [comment] 2024-07-26 20:11
> Using 49.20, I was able to load and play the game to completion, without hitting an NPE. The picture is from right after loading. [Battle.zip](https://github.com/user-attachments/files/16392416/Battle.zip)
May very well be the awful connection at work causing issues, then. I intend to test this tonight on my home PC as well

**Comment by TalRaziid** [comment] 2024-07-27 22:14
> May very well be the awful connection at work causing issues, then. I intend to test this tonight on my home PC as well

This was not the cause, i get this error at home as well

**Comment by TalRaziid** [comment] 2024-07-28 00:35
[Second NPE bug report.zip](https://github.com/user-attachments/files/16401835/Second.NPE.bug.report.zip)
Another NPE, in another battle. I managed to finish the last battle with /victory at home.

**Comment by HammerGS** [comment] 2024-07-28 00:44
@TalRaziid Can you elaborate on what was happening when the NPE happened.  Some type of Physical attack?




From the log

```
19:32:38,750 ERROR [mekhq.MekHQ] {Packet Pump}
mekhq.MekHQ.lambda$main$0(MekHQ.java:260) - Uncaught Exception Detected
java.lang.NullPointerException: Cannot invoke "megamek.common.Hex.containsTerrain(int)" because "hex" is null
	at megamek.common.Entity.isEligibleForPhysical(Entity.java:10039)
	at megamek.common.Entity.isEligibleFor(Entity.java:9896)
	at megamek.common.Infantry.isEligibleFor(Infantry.java:1106)
	at megamek.server.GameManager.setIneligible(GameManager.java:2890)
	at megamek.server.TWPhasePreparationManager.managePhase(TWPhasePreparationManager.java:161)
	at megamek.server.GameManager.prepareForCurrentPhase(GameManager.java:1695)
	at megamek.server.AbstractGameManager.changePhase(AbstractGameManager.java:88)
	at megamek.server.TWPhaseEndManager.managePhase(TWPhaseEndManager.java:152)
	at megamek.server.GameManager.endCurrentPhase(GameManager.java:1852)
	at megamek.server.GameManager.checkReady(GameManager.java:1250)
	at megamek.server.AbstractGameManager.handlePacket(AbstractGameManager.java:58)
	at megamek.server.GameManager.handlePacket(GameManager.java:592)
	at megamek.server.Server.handle(Server.java:1280)
	at megamek.server.Server$PacketPump.run(Server.java:113)
```

**Comment by HammerGS** [comment] 2024-07-28 01:03
Comment from Discord - "as Firing Report appeared, NPE"

Unit wasn't swarming but did have leg attacks.
![image](https://github.com/user-attachments/assets/3c85ead4-a786-4596-97ff-2a25b61948d1)


![image](https://github.com/user-attachments/assets/73f1fa0d-16ba-4564-86b6-2a2b49817aa8)

**Comment by TalRaziid** [comment] 2024-07-28 01:06
[Tal bugged sea-mangrovecliffs.zip](https://github.com/user-attachments/files/16401882/Tal.bugged.sea-mangrovecliffs.zip)
As requested

**Comment by repligator** [comment] 2024-07-28 01:23
`18:18:03,739 INFO  [megamek.common.util.ImageUtil.TileMapImageLoader] {AWT-EventQueue-0}
megamek.common.util.ImageUtil$TileMapImageLoader.loadImage(ImageUtil.java:319) - Loading atlas: data\images\universe\planets.png`
This is an asset for MHQ. Why is it showing up in the MM log?

It might just be that I'm not used to IPv6, but it looks like you have 5 different interfaces spread across 2 different networks (not counting link-local).

**Comment by TalRaziid** [comment] 2024-07-28 01:42
> `18:18:03,739 INFO [megamek.common.util.ImageUtil.TileMapImageLoader] {AWT-EventQueue-0} megamek.common.util.ImageUtil$TileMapImageLoader.loadImage(ImageUtil.java:319) - Loading atlas: data\images\universe\planets.png` This is an asset for MHQ. Why is it showing up in the MM log?
> 
> It might just be that I'm not used to IPv6, but it looks like you have 5 different interfaces spread across 2 different networks (not counting link-local).

I dont work here I just play MHQ campaigns my dood. I have my MHQ campaign, i launch MM battles from it like you're supposed to

**Comment by repligator** [comment] 2024-07-28 01:48
> > `18:18:03,739 INFO [megamek.common.util.ImageUtil.TileMapImageLoader] {AWT-EventQueue-0} megamek.common.util.ImageUtil$TileMapImageLoader.loadImage(ImageUtil.java:319) - Loading atlas: data\images\universe\planets.png` This is an asset for MHQ. Why is it showing up in the MM log?
> > It might just be that I'm not used to IPv6, but it looks like you have 5 different interfaces spread across 2 different networks (not counting link-local).
> 
> I dont work here I just play MHQ campaigns my dood. I have my MHQ campaign, i launch MM battles from it like you're supposed to

Sorry, the question wasn't meant to be directed towards you. I'm just "thinking out loud" so that other volunteers can either pursue something as a potential cause of the issue, or let me know it's just a false lead.

**Comment by Sleet01** [comment] 2024-07-28 07:50
@TalRaziid Any chance you'd picked up a unit in the movement phase of the error turn, previously?

I'm relatively certain that units loaded in this turn don't have a hex location, which would cause the error we're seeing.
Gonna check that angle.

**Comment by Sleet01** [comment] 2024-07-28 08:08
Yep, confirmed: the unit getting loaded this turn has a null location and no hex location, because it just got zooped up into a chopper.  I'll see if there are any other checks waiting to break, but I think this is a simple fix.

**Closed** 2024-07-28 20:19 UTC
Labels: Bug, MHQ-origin MM Issues

**Comment by TalRaziid** [comment] 2024-07-28 20:56
> @TalRaziid Any chance you'd picked up a unit in the movement phase of the error turn, previously?
> 
> I'm relatively certain that units loaded in this turn don't have a hex location, which would cause the error we're seeing. Gonna check that angle.

Sorry, Im unused to using git or anything for this kind of thing so im not seeing the messages until i check myself.  That seems likely!  Seems like it was fixed so thats cool.
