### ISSUE TITLE
NPE FiringDisplay.clear

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#1039] opened 2018-07-11 03:54 UTC
### Environment
MegaMek 0.44.0
Java 8
Win 8.1

### Description
![image](https://user-images.githubusercontent.com/16950832/42549850-f2959800-8493-11e8-98b2-ed1374e8774c.png)

I dont know what happened.  Obvious (Comstar) joined, were talking a little bit, I fired my remaining medium laser, the game kinda froze a little bit, and then the done button stayed greyed out and now I cannot advance the turn.  NPE at the bottom of the log for swing.FiringDisplay.clear

### Files
[megameklog.txt](https://github.com/MegaMek/megamek/files/2182887/megameklog.txt)
[ObviousBrokeIt.sav.gz](https://github.com/MegaMek/megamek/files/2182890/ObviousBrokeIt.sav.gz)

**Comment by NickAragua** [comment] 2018-07-16 01:11
Can't reproduce this - loading the save game, I can fire the laser and it advances to the battle armor.

**Comment by BLOODWOLF333** [comment] 2018-07-16 02:55
Yeah I think obvious was sending a message at the exact time I pressed escape to undo firing my laser and it caused the game to freeze and spit out that NPE in the log.  May never be able to reproduce those conditions again.  Might be the whole game not being threadsafe thing?

**Comment by neoancient** [comment] 2018-07-16 03:29
I don't think messages have anything to do with Game.

**Comment by Dirk-c-Walter** [comment] 2018-07-17 06:22
I have seen the same thing recently, can't replicate it.

I'll probably just make a patch that adds some sanity null checks and aborts the function if it is null. that should at least prevent the NPE's. Not a perfect fix, but unless we can generate them reliably it;s hard to fix.

**Comment by arlith** [comment] 2018-07-20 01:51
A null-guard on `ce()` is the answer here.  This should happen anytime you hit the clear key and it's not your turn.  This is because, when it's not your turn `cen` will be `ENTITY_NONE` and hence `ce()` returns null.  In fact, since it's such a quick fix, I'll just do it now.

On the otherhand, I don't think this has any real impact.  The exception will get absorbed by the AWT Event thread and things will keep on trucking.  It won't cause the issue @BLOODWOLF333 described, at least I don't think it will.

**Comment by arlith** [comment] 2018-07-20 01:57
I'm going to close this, since the failure of the done button can't be reproduced and all of the things in the log file are taken care of.

**Closed** 2018-07-20 01:57 UTC
Labels: Bug
