### ISSUE TITLE
[RFE] Allow ground units to walk off the board with remaining movement

### ISSUE THREAD

**Issue by KaiserFalk** [MegaMek/megamek#5250] opened 2024-03-14 23:04 UTC
Currently in order to walk off the board as a ground unit, you have to start your turn on the edge of the board. However, ASF can fly off the board, if they have any movement remaining. Is it possible to extend this behaviour to ground units as well?

**Comment by kuronekochomusuke** [comment] 2024-11-27 23:56
duplicate of #346

**Closed by kuronekochomusuke** 2024-11-27 23:56 UTC
Labels: (RFE) Enhancement, Map and Board
