### ISSUE TITLE
Stuck at transmitting game data 0.47.14

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#2501] opened 2020-12-12 02:26 UTC
### Environment
What version of MegaMek does your issue apply to?  Note whether it is the stand alone MegaMek or HQ's MegaMek.
MekHQ pack 0.47.14

What operating system are you using?  Windows, Mac, or Linux?
Win10

### Description
Units loaded to lobby, clicked done, saw "Transmitting game data" for a few minutes with no progress to deployment.

### Files
[transmitting_game_data_freezeup.sav.gz](https://github.com/MegaMek/megamek/files/5682348/transmitting_game_data_freezeup.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/5682352/megameklog.txt)

**Comment by BLR-IIC** [comment] 2020-12-12 02:51
After some more experimentation, this seems related to equipping the bomb bays of my team's LAMs with bombs.  When I don't select bombs for them in the lobby, the game proceeds through transmitting data.

**Comment by neoancient** [comment] 2020-12-12 20:54
I can't reproduce this. Whether I load the provided save or start new game with a LAM loaded with bombs, it proceeds to the deployment phase.

**Comment by BLR-IIC** [comment] 2020-12-12 21:47
I just tried the save on a different computer and I couldn't reproduce it either.  Perhaps it's a problem with the original computer I was using with this.  I think this rules out relation to the MekHQ bug.

**Comment by BLR-IIC** [comment] 2020-12-14 01:40
So out of curiosity, I tried the savegame in standalone MegaMek on the computer where I first found the issue.  When I loaded the savegame through MegaMek, I made it past the "transmitting game data" without an issue.  Whereas when I do it through MekHQ, it stops MegaMek there.

**Comment by BLR-IIC** [comment] 2020-12-20 02:18
There's something else I noticed about this:  Whenever I load bombs onto my units before I get stuck at "Transmitting", save the game, then reload it separately, the game does proceed, but my aerospace units are all missing their bombs that I loaded them with in the lobby before getting MegaMek stuck.

**Comment by HammerGS** [comment] 2024-10-26 15:49
Given the rework of bombs and being outdated closing this,

**Closed by HammerGS** 2024-10-26 15:49 UTC
Labels: Can't Reproduce, Outdated
