### ISSUE TITLE
Request: Add Role and Design Quirks on advanced search filter?

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megamek#1380] opened 2019-06-12 16:29 UTC
### Environment
Ver 0.45.4

### Description
Well, for now, you have walk/Jump MP, thickness of armor per its tonnage, cockpit type, internal structure, armor type, unit type, tech class, level, weapons&equipments and year on the unit.

But.. is it bad to add Role and Design Quirks on the filter? Although role is not matched properly, but it may a reference. And find out the units with the same quirk seems useful sometimes as well. If adding role and design quirks on the filter, how about to have the option to choose include/except some role or quirk?

Besides, is there any plan to allows to edit role of the unit on MegaMekLab? My customized units are cannot be assigned a role....

**Comment by HammerGS** [comment] 2023-01-23 15:58
Duplicate of https://github.com/MegaMek/megamek/issues/1953

**Closed by HammerGS** 2023-01-23 15:58 UTC
Labels: Enhancement, Quirks, GUI, Advanced Search, Duplicate
